// @generated by protoc-gen-es v2.16.0
// @generated from file admin/v1/cancelled_class.proto (package admin.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Date } from "../../google/type/date_pb";
import type { Period } from "./common_pb";
import type { FieldMask, Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file admin/v1/cancelled_class.proto.
 */
export declare const file_admin_v1_cancelled_class: GenFile;

/**
 * @generated from message admin.v1.CancelledClass
 */
export declare type CancelledClass = Message<"admin.v1.CancelledClass"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string subject_id = 2;
   */
  subjectId: string;

  /**
   * @generated from field: google.type.Date date = 3;
   */
  date?: Date | undefined;

  /**
   * @generated from field: admin.v1.Period period = 4;
   */
  period: Period;

  /**
   * @generated from field: optional string comment = 5;
   */
  comment?: string | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 6;
   */
  createdAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 7;
   */
  updatedAt?: Timestamp | undefined;
};

/**
 * Describes the message admin.v1.CancelledClass.
 * Use `create(CancelledClassSchema)` to create a new message.
 */
export declare const CancelledClassSchema: GenMessage<CancelledClass>;

/**
 * @generated from message admin.v1.ListCancelledClassesRequest
 */
export declare type ListCancelledClassesRequest = Message<"admin.v1.ListCancelledClassesRequest"> & {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;
};

/**
 * Describes the message admin.v1.ListCancelledClassesRequest.
 * Use `create(ListCancelledClassesRequestSchema)` to create a new message.
 */
export declare const ListCancelledClassesRequestSchema: GenMessage<ListCancelledClassesRequest>;

/**
 * @generated from message admin.v1.ListCancelledClassesResponse
 */
export declare type ListCancelledClassesResponse = Message<"admin.v1.ListCancelledClassesResponse"> & {
  /**
   * @generated from field: repeated admin.v1.CancelledClass cancelled_classes = 1;
   */
  cancelledClasses: CancelledClass[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message admin.v1.ListCancelledClassesResponse.
 * Use `create(ListCancelledClassesResponseSchema)` to create a new message.
 */
export declare const ListCancelledClassesResponseSchema: GenMessage<ListCancelledClassesResponse>;

/**
 * @generated from message admin.v1.GetCancelledClassRequest
 */
export declare type GetCancelledClassRequest = Message<"admin.v1.GetCancelledClassRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message admin.v1.GetCancelledClassRequest.
 * Use `create(GetCancelledClassRequestSchema)` to create a new message.
 */
export declare const GetCancelledClassRequestSchema: GenMessage<GetCancelledClassRequest>;

/**
 * @generated from message admin.v1.GetCancelledClassResponse
 */
export declare type GetCancelledClassResponse = Message<"admin.v1.GetCancelledClassResponse"> & {
  /**
   * @generated from field: admin.v1.CancelledClass cancelled_class = 1;
   */
  cancelledClass?: CancelledClass | undefined;
};

/**
 * Describes the message admin.v1.GetCancelledClassResponse.
 * Use `create(GetCancelledClassResponseSchema)` to create a new message.
 */
export declare const GetCancelledClassResponseSchema: GenMessage<GetCancelledClassResponse>;

/**
 * @generated from message admin.v1.CreateCancelledClassRequest
 */
export declare type CreateCancelledClassRequest = Message<"admin.v1.CreateCancelledClassRequest"> & {
  /**
   * @generated from field: string subject_id = 1;
   */
  subjectId: string;

  /**
   * @generated from field: google.type.Date date = 2;
   */
  date?: Date | undefined;

  /**
   * @generated from field: admin.v1.Period period = 3;
   */
  period: Period;

  /**
   * @generated from field: optional string comment = 4;
   */
  comment?: string | undefined;
};

/**
 * Describes the message admin.v1.CreateCancelledClassRequest.
 * Use `create(CreateCancelledClassRequestSchema)` to create a new message.
 */
export declare const CreateCancelledClassRequestSchema: GenMessage<CreateCancelledClassRequest>;

/**
 * @generated from message admin.v1.CreateCancelledClassResponse
 */
export declare type CreateCancelledClassResponse = Message<"admin.v1.CreateCancelledClassResponse"> & {
  /**
   * @generated from field: admin.v1.CancelledClass cancelled_class = 1;
   */
  cancelledClass?: CancelledClass | undefined;
};

/**
 * Describes the message admin.v1.CreateCancelledClassResponse.
 * Use `create(CreateCancelledClassResponseSchema)` to create a new message.
 */
export declare const CreateCancelledClassResponseSchema: GenMessage<CreateCancelledClassResponse>;

/**
 * @generated from message admin.v1.UpdateCancelledClassRequest
 */
export declare type UpdateCancelledClassRequest = Message<"admin.v1.UpdateCancelledClassRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string subject_id = 2;
   */
  subjectId: string;

  /**
   * @generated from field: google.type.Date date = 3;
   */
  date?: Date | undefined;

  /**
   * @generated from field: admin.v1.Period period = 4;
   */
  period: Period;

  /**
   * @generated from field: optional string comment = 5;
   */
  comment?: string | undefined;

  /**
   * @generated from field: google.protobuf.FieldMask update_mask = 99;
   */
  updateMask?: FieldMask | undefined;
};

/**
 * Describes the message admin.v1.UpdateCancelledClassRequest.
 * Use `create(UpdateCancelledClassRequestSchema)` to create a new message.
 */
export declare const UpdateCancelledClassRequestSchema: GenMessage<UpdateCancelledClassRequest>;

/**
 * @generated from message admin.v1.UpdateCancelledClassResponse
 */
export declare type UpdateCancelledClassResponse = Message<"admin.v1.UpdateCancelledClassResponse"> & {
  /**
   * @generated from field: admin.v1.CancelledClass cancelled_class = 1;
   */
  cancelledClass?: CancelledClass | undefined;
};

/**
 * Describes the message admin.v1.UpdateCancelledClassResponse.
 * Use `create(UpdateCancelledClassResponseSchema)` to create a new message.
 */
export declare const UpdateCancelledClassResponseSchema: GenMessage<UpdateCancelledClassResponse>;

/**
 * @generated from message admin.v1.DeleteCancelledClassRequest
 */
export declare type DeleteCancelledClassRequest = Message<"admin.v1.DeleteCancelledClassRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message admin.v1.DeleteCancelledClassRequest.
 * Use `create(DeleteCancelledClassRequestSchema)` to create a new message.
 */
export declare const DeleteCancelledClassRequestSchema: GenMessage<DeleteCancelledClassRequest>;

/**
 * @generated from message admin.v1.DeleteCancelledClassResponse
 */
export declare type DeleteCancelledClassResponse = Message<"admin.v1.DeleteCancelledClassResponse"> & {
};

/**
 * Describes the message admin.v1.DeleteCancelledClassResponse.
 * Use `create(DeleteCancelledClassResponseSchema)` to create a new message.
 */
export declare const DeleteCancelledClassResponseSchema: GenMessage<DeleteCancelledClassResponse>;

/**
 * @generated from service admin.v1.CancelledClassService
 */
export declare const CancelledClassService: GenService<{
  /**
   * @generated from rpc admin.v1.CancelledClassService.ListCancelledClasses
   */
  listCancelledClasses: {
    methodKind: "unary";
    input: typeof ListCancelledClassesRequestSchema;
    output: typeof ListCancelledClassesResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.CancelledClassService.GetCancelledClass
   */
  getCancelledClass: {
    methodKind: "unary";
    input: typeof GetCancelledClassRequestSchema;
    output: typeof GetCancelledClassResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.CancelledClassService.CreateCancelledClass
   */
  createCancelledClass: {
    methodKind: "unary";
    input: typeof CreateCancelledClassRequestSchema;
    output: typeof CreateCancelledClassResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.CancelledClassService.UpdateCancelledClass
   */
  updateCancelledClass: {
    methodKind: "unary";
    input: typeof UpdateCancelledClassRequestSchema;
    output: typeof UpdateCancelledClassResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.CancelledClassService.DeleteCancelledClass
   */
  deleteCancelledClass: {
    methodKind: "unary";
    input: typeof DeleteCancelledClassRequestSchema;
    output: typeof DeleteCancelledClassResponseSchema;
  },
}>;

