// @generated by protoc-gen-es v2.16.0
// @generated from file admin/v1/common.proto (package admin.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file admin/v1/common.proto.
 */
export declare const file_admin_v1_common: GenFile;

/**
 * @generated from enum admin.v1.Grade
 */
export enum Grade {
  /**
   * @generated from enum value: GRADE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: GRADE_B1 = 1;
   */
  B1 = 1,

  /**
   * @generated from enum value: GRADE_B2 = 2;
   */
  B2 = 2,

  /**
   * @generated from enum value: GRADE_B3 = 3;
   */
  B3 = 3,

  /**
   * @generated from enum value: GRADE_B4 = 4;
   */
  B4 = 4,

  /**
   * @generated from enum value: GRADE_M1 = 5;
   */
  M1 = 5,

  /**
   * @generated from enum value: GRADE_M2 = 6;
   */
  M2 = 6,

  /**
   * @generated from enum value: GRADE_D1 = 7;
   */
  D1 = 7,

  /**
   * @generated from enum value: GRADE_D2 = 8;
   */
  D2 = 8,

  /**
   * @generated from enum value: GRADE_D3 = 9;
   */
  D3 = 9,
}

/**
 * Describes the enum admin.v1.Grade.
 */
export declare const GradeSchema: GenEnum<Grade>;

/**
 * @generated from enum admin.v1.Course
 */
export enum Course {
  /**
   * @generated from enum value: COURSE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: COURSE_INFORMATION_SYSTEM = 1;
   */
  INFORMATION_SYSTEM = 1,

  /**
   * @generated from enum value: COURSE_INFORMATION_DESIGN = 2;
   */
  INFORMATION_DESIGN = 2,

  /**
   * @generated from enum value: COURSE_ADVANCED_ICT = 3;
   */
  ADVANCED_ICT = 3,

  /**
   * @generated from enum value: COURSE_COMPLEX_SYSTEM = 4;
   */
  COMPLEX_SYSTEM = 4,

  /**
   * @generated from enum value: COURSE_INTELLIGENT_SYSTEM = 5;
   */
  INTELLIGENT_SYSTEM = 5,
}

/**
 * Describes the enum admin.v1.Course.
 */
export declare const CourseSchema: GenEnum<Course>;

/**
 * @generated from enum admin.v1.Class
 */
export enum Class {
  /**
   * @generated from enum value: CLASS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: CLASS_A = 1;
   */
  A = 1,

  /**
   * @generated from enum value: CLASS_B = 2;
   */
  B = 2,

  /**
   * @generated from enum value: CLASS_C = 3;
   */
  C = 3,

  /**
   * @generated from enum value: CLASS_D = 4;
   */
  D = 4,

  /**
   * @generated from enum value: CLASS_E = 5;
   */
  E = 5,

  /**
   * @generated from enum value: CLASS_F = 6;
   */
  F = 6,

  /**
   * @generated from enum value: CLASS_G = 7;
   */
  G = 7,

  /**
   * @generated from enum value: CLASS_H = 8;
   */
  H = 8,

  /**
   * @generated from enum value: CLASS_I = 9;
   */
  I = 9,

  /**
   * @generated from enum value: CLASS_J = 10;
   */
  J = 10,

  /**
   * @generated from enum value: CLASS_K = 11;
   */
  K = 11,

  /**
   * @generated from enum value: CLASS_L = 12;
   */
  L = 12,
}

/**
 * Describes the enum admin.v1.Class.
 */
export declare const ClassSchema: GenEnum<Class>;

/**
 * @generated from enum admin.v1.Period
 */
export enum Period {
  /**
   * @generated from enum value: PERIOD_UNSPECIFIED = 0;
   */
  PERIOD_UNSPECIFIED = 0,

  /**
   * @generated from enum value: PERIOD_1 = 1;
   */
  PERIOD_1 = 1,

  /**
   * @generated from enum value: PERIOD_2 = 2;
   */
  PERIOD_2 = 2,

  /**
   * @generated from enum value: PERIOD_3 = 3;
   */
  PERIOD_3 = 3,

  /**
   * @generated from enum value: PERIOD_4 = 4;
   */
  PERIOD_4 = 4,

  /**
   * @generated from enum value: PERIOD_5 = 5;
   */
  PERIOD_5 = 5,

  /**
   * @generated from enum value: PERIOD_6 = 6;
   */
  PERIOD_6 = 6,
}

/**
 * Describes the enum admin.v1.Period.
 */
export declare const PeriodSchema: GenEnum<Period>;

