// @generated by protoc-gen-es v2.16.0
// @generated from file admin/v1/common.proto (package admin.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file admin/v1/common.proto.
 */
export const file_admin_v1_common = /*@__PURE__*/
  fileDesc("ChVhZG1pbi92MS9jb21tb24ucHJvdG8SCGFkbWluLnYxKpwBCgVHcmFkZRIVChFHUkFERV9VTlNQRUNJRklFRBAAEgwKCEdSQURFX0IxEAESDAoIR1JBREVfQjIQAhIMCghHUkFERV9CMxADEgwKCEdSQURFX0I0EAQSDAoIR1JBREVfTTEQBRIMCghHUkFERV9NMhAGEgwKCEdSQURFX0QxEAcSDAoIR1JBREVfRDIQCBIMCghHUkFERV9EMxAJKrEBCgZDb3Vyc2USFgoSQ09VUlNFX1VOU1BFQ0lGSUVEEAASHQoZQ09VUlNFX0lORk9STUFUSU9OX1NZU1RFTRABEh0KGUNPVVJTRV9JTkZPUk1BVElPTl9ERVNJR04QAhIXChNDT1VSU0VfQURWQU5DRURfSUNUEAMSGQoVQ09VUlNFX0NPTVBMRVhfU1lTVEVNEAQSHQoZQ09VUlNFX0lOVEVMTElHRU5UX1NZU1RFTRAFKroBCgVDbGFzcxIVChFDTEFTU19VTlNQRUNJRklFRBAAEgsKB0NMQVNTX0EQARILCgdDTEFTU19CEAISCwoHQ0xBU1NfQxADEgsKB0NMQVNTX0QQBBILCgdDTEFTU19FEAUSCwoHQ0xBU1NfRhAGEgsKB0NMQVNTX0cQBxILCgdDTEFTU19IEAgSCwoHQ0xBU1NfSRAJEgsKB0NMQVNTX0oQChILCgdDTEFTU19LEAsSCwoHQ0xBU1NfTBAMKnQKBlBlcmlvZBIWChJQRVJJT0RfVU5TUEVDSUZJRUQQABIMCghQRVJJT0RfMRABEgwKCFBFUklPRF8yEAISDAoIUEVSSU9EXzMQAxIMCghQRVJJT0RfNBAEEgwKCFBFUklPRF81EAUSDAoIUEVSSU9EXzYQBmIGcHJvdG8z");

/**
 * Describes the enum admin.v1.Grade.
 */
export const GradeSchema = /*@__PURE__*/
  enumDesc(file_admin_v1_common, 0);

/**
 * @generated from enum admin.v1.Grade
 */
export const Grade = /*@__PURE__*/
  tsEnum(GradeSchema);

/**
 * Describes the enum admin.v1.Course.
 */
export const CourseSchema = /*@__PURE__*/
  enumDesc(file_admin_v1_common, 1);

/**
 * @generated from enum admin.v1.Course
 */
export const Course = /*@__PURE__*/
  tsEnum(CourseSchema);

/**
 * Describes the enum admin.v1.Class.
 */
export const ClassSchema = /*@__PURE__*/
  enumDesc(file_admin_v1_common, 2);

/**
 * @generated from enum admin.v1.Class
 */
export const Class = /*@__PURE__*/
  tsEnum(ClassSchema);

/**
 * Describes the enum admin.v1.Period.
 */
export const PeriodSchema = /*@__PURE__*/
  enumDesc(file_admin_v1_common, 3);

/**
 * @generated from enum admin.v1.Period
 */
export const Period = /*@__PURE__*/
  tsEnum(PeriodSchema);

