// @generated by protoc-gen-es v2.16.0
// @generated from file admin/v1/course_registration.proto (package admin.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file admin/v1/course_registration.proto.
 */
export const file_admin_v1_course_registration = /*@__PURE__*/
  fileDesc("CiJhZG1pbi92MS9jb3Vyc2VfcmVnaXN0cmF0aW9uLnByb3RvEghhZG1pbi52MSKZAQoSQ291cnNlUmVnaXN0cmF0aW9uEg8KB3VzZXJfaWQYASABKAkSEgoKc3ViamVjdF9pZBgCIAEoCRIuCgpjcmVhdGVkX2F0GAMgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgp1cGRhdGVkX2F0GAQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCJHCh5MaXN0Q291cnNlUmVnaXN0cmF0aW9uc1JlcXVlc3QSEQoJcGFnZV9zaXplGAEgASgFEhIKCnBhZ2VfdG9rZW4YAiABKAkidgofTGlzdENvdXJzZVJlZ2lzdHJhdGlvbnNSZXNwb25zZRI6ChRjb3Vyc2VfcmVnaXN0cmF0aW9ucxgBIAMoCzIcLmFkbWluLnYxLkNvdXJzZVJlZ2lzdHJhdGlvbhIXCg9uZXh0X3BhZ2VfdG9rZW4YAiABKAkiQwocR2V0Q291cnNlUmVnaXN0cmF0aW9uUmVxdWVzdBIPCgd1c2VyX2lkGAEgASgJEhIKCnN1YmplY3RfaWQYAiABKAkiWgodR2V0Q291cnNlUmVnaXN0cmF0aW9uUmVzcG9uc2USOQoTY291cnNlX3JlZ2lzdHJhdGlvbhgBIAEoCzIcLmFkbWluLnYxLkNvdXJzZVJlZ2lzdHJhdGlvbiJGCh9DcmVhdGVDb3Vyc2VSZWdpc3RyYXRpb25SZXF1ZXN0Eg8KB3VzZXJfaWQYASABKAkSEgoKc3ViamVjdF9pZBgCIAEoCSJdCiBDcmVhdGVDb3Vyc2VSZWdpc3RyYXRpb25SZXNwb25zZRI5ChNjb3Vyc2VfcmVnaXN0cmF0aW9uGAEgASgLMhwuYWRtaW4udjEuQ291cnNlUmVnaXN0cmF0aW9uIkYKH0RlbGV0ZUNvdXJzZVJlZ2lzdHJhdGlvblJlcXVlc3QSDwoHdXNlcl9pZBgBIAEoCRISCgpzdWJqZWN0X2lkGAIgASgJIiIKIERlbGV0ZUNvdXJzZVJlZ2lzdHJhdGlvblJlc3BvbnNlMtsDChlDb3Vyc2VSZWdpc3RyYXRpb25TZXJ2aWNlEm4KF0xpc3RDb3Vyc2VSZWdpc3RyYXRpb25zEiguYWRtaW4udjEuTGlzdENvdXJzZVJlZ2lzdHJhdGlvbnNSZXF1ZXN0GikuYWRtaW4udjEuTGlzdENvdXJzZVJlZ2lzdHJhdGlvbnNSZXNwb25zZRJoChVHZXRDb3Vyc2VSZWdpc3RyYXRpb24SJi5hZG1pbi52MS5HZXRDb3Vyc2VSZWdpc3RyYXRpb25SZXF1ZXN0GicuYWRtaW4udjEuR2V0Q291cnNlUmVnaXN0cmF0aW9uUmVzcG9uc2UScQoYQ3JlYXRlQ291cnNlUmVnaXN0cmF0aW9uEikuYWRtaW4udjEuQ3JlYXRlQ291cnNlUmVnaXN0cmF0aW9uUmVxdWVzdBoqLmFkbWluLnYxLkNyZWF0ZUNvdXJzZVJlZ2lzdHJhdGlvblJlc3BvbnNlEnEKGERlbGV0ZUNvdXJzZVJlZ2lzdHJhdGlvbhIpLmFkbWluLnYxLkRlbGV0ZUNvdXJzZVJlZ2lzdHJhdGlvblJlcXVlc3QaKi5hZG1pbi52MS5EZWxldGVDb3Vyc2VSZWdpc3RyYXRpb25SZXNwb25zZWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * Describes the message admin.v1.CourseRegistration.
 * Use `create(CourseRegistrationSchema)` to create a new message.
 */
export const CourseRegistrationSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_course_registration, 0);

/**
 * Describes the message admin.v1.ListCourseRegistrationsRequest.
 * Use `create(ListCourseRegistrationsRequestSchema)` to create a new message.
 */
export const ListCourseRegistrationsRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_course_registration, 1);

/**
 * Describes the message admin.v1.ListCourseRegistrationsResponse.
 * Use `create(ListCourseRegistrationsResponseSchema)` to create a new message.
 */
export const ListCourseRegistrationsResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_course_registration, 2);

/**
 * Describes the message admin.v1.GetCourseRegistrationRequest.
 * Use `create(GetCourseRegistrationRequestSchema)` to create a new message.
 */
export const GetCourseRegistrationRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_course_registration, 3);

/**
 * Describes the message admin.v1.GetCourseRegistrationResponse.
 * Use `create(GetCourseRegistrationResponseSchema)` to create a new message.
 */
export const GetCourseRegistrationResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_course_registration, 4);

/**
 * Describes the message admin.v1.CreateCourseRegistrationRequest.
 * Use `create(CreateCourseRegistrationRequestSchema)` to create a new message.
 */
export const CreateCourseRegistrationRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_course_registration, 5);

/**
 * Describes the message admin.v1.CreateCourseRegistrationResponse.
 * Use `create(CreateCourseRegistrationResponseSchema)` to create a new message.
 */
export const CreateCourseRegistrationResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_course_registration, 6);

/**
 * Describes the message admin.v1.DeleteCourseRegistrationRequest.
 * Use `create(DeleteCourseRegistrationRequestSchema)` to create a new message.
 */
export const DeleteCourseRegistrationRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_course_registration, 7);

/**
 * Describes the message admin.v1.DeleteCourseRegistrationResponse.
 * Use `create(DeleteCourseRegistrationResponseSchema)` to create a new message.
 */
export const DeleteCourseRegistrationResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_course_registration, 8);

/**
 * @generated from service admin.v1.CourseRegistrationService
 */
export const CourseRegistrationService = /*@__PURE__*/
  serviceDesc(file_admin_v1_course_registration, 0);

