// @generated by protoc-gen-es v2.16.0
// @generated from file admin/v1/course_registration.proto (package admin.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file admin/v1/course_registration.proto.
 */
export declare const file_admin_v1_course_registration: GenFile;

/**
 * @generated from message admin.v1.CourseRegistration
 */
export declare type CourseRegistration = Message<"admin.v1.CourseRegistration"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string subject_id = 2;
   */
  subjectId: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 3;
   */
  createdAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 4;
   */
  updatedAt?: Timestamp | undefined;
};

/**
 * Describes the message admin.v1.CourseRegistration.
 * Use `create(CourseRegistrationSchema)` to create a new message.
 */
export declare const CourseRegistrationSchema: GenMessage<CourseRegistration>;

/**
 * @generated from message admin.v1.ListCourseRegistrationsRequest
 */
export declare type ListCourseRegistrationsRequest = Message<"admin.v1.ListCourseRegistrationsRequest"> & {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;
};

/**
 * Describes the message admin.v1.ListCourseRegistrationsRequest.
 * Use `create(ListCourseRegistrationsRequestSchema)` to create a new message.
 */
export declare const ListCourseRegistrationsRequestSchema: GenMessage<ListCourseRegistrationsRequest>;

/**
 * @generated from message admin.v1.ListCourseRegistrationsResponse
 */
export declare type ListCourseRegistrationsResponse = Message<"admin.v1.ListCourseRegistrationsResponse"> & {
  /**
   * @generated from field: repeated admin.v1.CourseRegistration course_registrations = 1;
   */
  courseRegistrations: CourseRegistration[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message admin.v1.ListCourseRegistrationsResponse.
 * Use `create(ListCourseRegistrationsResponseSchema)` to create a new message.
 */
export declare const ListCourseRegistrationsResponseSchema: GenMessage<ListCourseRegistrationsResponse>;

/**
 * @generated from message admin.v1.GetCourseRegistrationRequest
 */
export declare type GetCourseRegistrationRequest = Message<"admin.v1.GetCourseRegistrationRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string subject_id = 2;
   */
  subjectId: string;
};

/**
 * Describes the message admin.v1.GetCourseRegistrationRequest.
 * Use `create(GetCourseRegistrationRequestSchema)` to create a new message.
 */
export declare const GetCourseRegistrationRequestSchema: GenMessage<GetCourseRegistrationRequest>;

/**
 * @generated from message admin.v1.GetCourseRegistrationResponse
 */
export declare type GetCourseRegistrationResponse = Message<"admin.v1.GetCourseRegistrationResponse"> & {
  /**
   * @generated from field: admin.v1.CourseRegistration course_registration = 1;
   */
  courseRegistration?: CourseRegistration | undefined;
};

/**
 * Describes the message admin.v1.GetCourseRegistrationResponse.
 * Use `create(GetCourseRegistrationResponseSchema)` to create a new message.
 */
export declare const GetCourseRegistrationResponseSchema: GenMessage<GetCourseRegistrationResponse>;

/**
 * @generated from message admin.v1.CreateCourseRegistrationRequest
 */
export declare type CreateCourseRegistrationRequest = Message<"admin.v1.CreateCourseRegistrationRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string subject_id = 2;
   */
  subjectId: string;
};

/**
 * Describes the message admin.v1.CreateCourseRegistrationRequest.
 * Use `create(CreateCourseRegistrationRequestSchema)` to create a new message.
 */
export declare const CreateCourseRegistrationRequestSchema: GenMessage<CreateCourseRegistrationRequest>;

/**
 * @generated from message admin.v1.CreateCourseRegistrationResponse
 */
export declare type CreateCourseRegistrationResponse = Message<"admin.v1.CreateCourseRegistrationResponse"> & {
  /**
   * @generated from field: admin.v1.CourseRegistration course_registration = 1;
   */
  courseRegistration?: CourseRegistration | undefined;
};

/**
 * Describes the message admin.v1.CreateCourseRegistrationResponse.
 * Use `create(CreateCourseRegistrationResponseSchema)` to create a new message.
 */
export declare const CreateCourseRegistrationResponseSchema: GenMessage<CreateCourseRegistrationResponse>;

/**
 * @generated from message admin.v1.DeleteCourseRegistrationRequest
 */
export declare type DeleteCourseRegistrationRequest = Message<"admin.v1.DeleteCourseRegistrationRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string subject_id = 2;
   */
  subjectId: string;
};

/**
 * Describes the message admin.v1.DeleteCourseRegistrationRequest.
 * Use `create(DeleteCourseRegistrationRequestSchema)` to create a new message.
 */
export declare const DeleteCourseRegistrationRequestSchema: GenMessage<DeleteCourseRegistrationRequest>;

/**
 * @generated from message admin.v1.DeleteCourseRegistrationResponse
 */
export declare type DeleteCourseRegistrationResponse = Message<"admin.v1.DeleteCourseRegistrationResponse"> & {
};

/**
 * Describes the message admin.v1.DeleteCourseRegistrationResponse.
 * Use `create(DeleteCourseRegistrationResponseSchema)` to create a new message.
 */
export declare const DeleteCourseRegistrationResponseSchema: GenMessage<DeleteCourseRegistrationResponse>;

/**
 * @generated from service admin.v1.CourseRegistrationService
 */
export declare const CourseRegistrationService: GenService<{
  /**
   * @generated from rpc admin.v1.CourseRegistrationService.ListCourseRegistrations
   */
  listCourseRegistrations: {
    methodKind: "unary";
    input: typeof ListCourseRegistrationsRequestSchema;
    output: typeof ListCourseRegistrationsResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.CourseRegistrationService.GetCourseRegistration
   */
  getCourseRegistration: {
    methodKind: "unary";
    input: typeof GetCourseRegistrationRequestSchema;
    output: typeof GetCourseRegistrationResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.CourseRegistrationService.CreateCourseRegistration
   */
  createCourseRegistration: {
    methodKind: "unary";
    input: typeof CreateCourseRegistrationRequestSchema;
    output: typeof CreateCourseRegistrationResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.CourseRegistrationService.DeleteCourseRegistration
   */
  deleteCourseRegistration: {
    methodKind: "unary";
    input: typeof DeleteCourseRegistrationRequestSchema;
    output: typeof DeleteCourseRegistrationResponseSchema;
  },
}>;

