// @generated by protoc-gen-es v2.16.0
// @generated from file admin/v1/faculty_room.proto (package admin.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file admin/v1/faculty_room.proto.
 */
export declare const file_admin_v1_faculty_room: GenFile;

/**
 * @generated from message admin.v1.FacultyRoom
 */
export declare type FacultyRoom = Message<"admin.v1.FacultyRoom"> & {
  /**
   * @generated from field: string faculty_id = 1;
   */
  facultyId: string;

  /**
   * @generated from field: string room_id = 2;
   */
  roomId: string;

  /**
   * @generated from field: int32 year = 3;
   */
  year: number;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 4;
   */
  createdAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 5;
   */
  updatedAt?: Timestamp | undefined;
};

/**
 * Describes the message admin.v1.FacultyRoom.
 * Use `create(FacultyRoomSchema)` to create a new message.
 */
export declare const FacultyRoomSchema: GenMessage<FacultyRoom>;

/**
 * @generated from message admin.v1.ListFacultyRoomsRequest
 */
export declare type ListFacultyRoomsRequest = Message<"admin.v1.ListFacultyRoomsRequest"> & {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;
};

/**
 * Describes the message admin.v1.ListFacultyRoomsRequest.
 * Use `create(ListFacultyRoomsRequestSchema)` to create a new message.
 */
export declare const ListFacultyRoomsRequestSchema: GenMessage<ListFacultyRoomsRequest>;

/**
 * @generated from message admin.v1.ListFacultyRoomsResponse
 */
export declare type ListFacultyRoomsResponse = Message<"admin.v1.ListFacultyRoomsResponse"> & {
  /**
   * @generated from field: repeated admin.v1.FacultyRoom faculty_rooms = 1;
   */
  facultyRooms: FacultyRoom[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message admin.v1.ListFacultyRoomsResponse.
 * Use `create(ListFacultyRoomsResponseSchema)` to create a new message.
 */
export declare const ListFacultyRoomsResponseSchema: GenMessage<ListFacultyRoomsResponse>;

/**
 * @generated from message admin.v1.GetFacultyRoomRequest
 */
export declare type GetFacultyRoomRequest = Message<"admin.v1.GetFacultyRoomRequest"> & {
  /**
   * @generated from field: string faculty_id = 1;
   */
  facultyId: string;

  /**
   * @generated from field: string room_id = 2;
   */
  roomId: string;

  /**
   * @generated from field: int32 year = 3;
   */
  year: number;
};

/**
 * Describes the message admin.v1.GetFacultyRoomRequest.
 * Use `create(GetFacultyRoomRequestSchema)` to create a new message.
 */
export declare const GetFacultyRoomRequestSchema: GenMessage<GetFacultyRoomRequest>;

/**
 * @generated from message admin.v1.GetFacultyRoomResponse
 */
export declare type GetFacultyRoomResponse = Message<"admin.v1.GetFacultyRoomResponse"> & {
  /**
   * @generated from field: admin.v1.FacultyRoom faculty_room = 1;
   */
  facultyRoom?: FacultyRoom | undefined;
};

/**
 * Describes the message admin.v1.GetFacultyRoomResponse.
 * Use `create(GetFacultyRoomResponseSchema)` to create a new message.
 */
export declare const GetFacultyRoomResponseSchema: GenMessage<GetFacultyRoomResponse>;

/**
 * @generated from message admin.v1.CreateFacultyRoomRequest
 */
export declare type CreateFacultyRoomRequest = Message<"admin.v1.CreateFacultyRoomRequest"> & {
  /**
   * @generated from field: string faculty_id = 1;
   */
  facultyId: string;

  /**
   * @generated from field: string room_id = 2;
   */
  roomId: string;

  /**
   * @generated from field: int32 year = 3;
   */
  year: number;
};

/**
 * Describes the message admin.v1.CreateFacultyRoomRequest.
 * Use `create(CreateFacultyRoomRequestSchema)` to create a new message.
 */
export declare const CreateFacultyRoomRequestSchema: GenMessage<CreateFacultyRoomRequest>;

/**
 * @generated from message admin.v1.CreateFacultyRoomResponse
 */
export declare type CreateFacultyRoomResponse = Message<"admin.v1.CreateFacultyRoomResponse"> & {
  /**
   * @generated from field: admin.v1.FacultyRoom faculty_room = 1;
   */
  facultyRoom?: FacultyRoom | undefined;
};

/**
 * Describes the message admin.v1.CreateFacultyRoomResponse.
 * Use `create(CreateFacultyRoomResponseSchema)` to create a new message.
 */
export declare const CreateFacultyRoomResponseSchema: GenMessage<CreateFacultyRoomResponse>;

/**
 * @generated from message admin.v1.DeleteFacultyRoomRequest
 */
export declare type DeleteFacultyRoomRequest = Message<"admin.v1.DeleteFacultyRoomRequest"> & {
  /**
   * @generated from field: string faculty_id = 1;
   */
  facultyId: string;

  /**
   * @generated from field: string room_id = 2;
   */
  roomId: string;

  /**
   * @generated from field: int32 year = 3;
   */
  year: number;
};

/**
 * Describes the message admin.v1.DeleteFacultyRoomRequest.
 * Use `create(DeleteFacultyRoomRequestSchema)` to create a new message.
 */
export declare const DeleteFacultyRoomRequestSchema: GenMessage<DeleteFacultyRoomRequest>;

/**
 * @generated from message admin.v1.DeleteFacultyRoomResponse
 */
export declare type DeleteFacultyRoomResponse = Message<"admin.v1.DeleteFacultyRoomResponse"> & {
};

/**
 * Describes the message admin.v1.DeleteFacultyRoomResponse.
 * Use `create(DeleteFacultyRoomResponseSchema)` to create a new message.
 */
export declare const DeleteFacultyRoomResponseSchema: GenMessage<DeleteFacultyRoomResponse>;

/**
 * @generated from service admin.v1.FacultyRoomService
 */
export declare const FacultyRoomService: GenService<{
  /**
   * @generated from rpc admin.v1.FacultyRoomService.ListFacultyRooms
   */
  listFacultyRooms: {
    methodKind: "unary";
    input: typeof ListFacultyRoomsRequestSchema;
    output: typeof ListFacultyRoomsResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.FacultyRoomService.GetFacultyRoom
   */
  getFacultyRoom: {
    methodKind: "unary";
    input: typeof GetFacultyRoomRequestSchema;
    output: typeof GetFacultyRoomResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.FacultyRoomService.CreateFacultyRoom
   */
  createFacultyRoom: {
    methodKind: "unary";
    input: typeof CreateFacultyRoomRequestSchema;
    output: typeof CreateFacultyRoomResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.FacultyRoomService.DeleteFacultyRoom
   */
  deleteFacultyRoom: {
    methodKind: "unary";
    input: typeof DeleteFacultyRoomRequestSchema;
    output: typeof DeleteFacultyRoomResponseSchema;
  },
}>;

