// @generated by protoc-gen-es v2.16.0
// @generated from file admin/v1/faculty.proto (package admin.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_field_mask, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file admin/v1/faculty.proto.
 */
export const file_admin_v1_faculty = /*@__PURE__*/
  fileDesc("ChZhZG1pbi92MS9mYWN1bHR5LnByb3RvEghhZG1pbi52MSKSAQoHRmFjdWx0eRIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJEg0KBWVtYWlsGAMgASgJEi4KCmNyZWF0ZWRfYXQYBCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4KCnVwZGF0ZWRfYXQYBSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wIj0KFExpc3RGYWN1bHRpZXNSZXF1ZXN0EhEKCXBhZ2Vfc2l6ZRgBIAEoBRISCgpwYWdlX3Rva2VuGAIgASgJIlYKFUxpc3RGYWN1bHRpZXNSZXNwb25zZRIkCglmYWN1bHRpZXMYASADKAsyES5hZG1pbi52MS5GYWN1bHR5EhcKD25leHRfcGFnZV90b2tlbhgCIAEoCSIfChFHZXRGYWN1bHR5UmVxdWVzdBIKCgJpZBgBIAEoCSI4ChJHZXRGYWN1bHR5UmVzcG9uc2USIgoHZmFjdWx0eRgBIAEoCzIRLmFkbWluLnYxLkZhY3VsdHkiMwoUQ3JlYXRlRmFjdWx0eVJlcXVlc3QSDAoEbmFtZRgBIAEoCRINCgVlbWFpbBgCIAEoCSI7ChVDcmVhdGVGYWN1bHR5UmVzcG9uc2USIgoHZmFjdWx0eRgBIAEoCzIRLmFkbWluLnYxLkZhY3VsdHkicAoUVXBkYXRlRmFjdWx0eVJlcXVlc3QSCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRINCgVlbWFpbBgDIAEoCRIvCgt1cGRhdGVfbWFzaxhjIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5GaWVsZE1hc2siOwoVVXBkYXRlRmFjdWx0eVJlc3BvbnNlEiIKB2ZhY3VsdHkYASABKAsyES5hZG1pbi52MS5GYWN1bHR5IiIKFERlbGV0ZUZhY3VsdHlSZXF1ZXN0EgoKAmlkGAEgASgJIhcKFURlbGV0ZUZhY3VsdHlSZXNwb25zZTKhAwoORmFjdWx0eVNlcnZpY2USUAoNTGlzdEZhY3VsdGllcxIeLmFkbWluLnYxLkxpc3RGYWN1bHRpZXNSZXF1ZXN0Gh8uYWRtaW4udjEuTGlzdEZhY3VsdGllc1Jlc3BvbnNlEkcKCkdldEZhY3VsdHkSGy5hZG1pbi52MS5HZXRGYWN1bHR5UmVxdWVzdBocLmFkbWluLnYxLkdldEZhY3VsdHlSZXNwb25zZRJQCg1DcmVhdGVGYWN1bHR5Eh4uYWRtaW4udjEuQ3JlYXRlRmFjdWx0eVJlcXVlc3QaHy5hZG1pbi52MS5DcmVhdGVGYWN1bHR5UmVzcG9uc2USUAoNVXBkYXRlRmFjdWx0eRIeLmFkbWluLnYxLlVwZGF0ZUZhY3VsdHlSZXF1ZXN0Gh8uYWRtaW4udjEuVXBkYXRlRmFjdWx0eVJlc3BvbnNlElAKDURlbGV0ZUZhY3VsdHkSHi5hZG1pbi52MS5EZWxldGVGYWN1bHR5UmVxdWVzdBofLmFkbWluLnYxLkRlbGV0ZUZhY3VsdHlSZXNwb25zZWIGcHJvdG8z", [file_google_protobuf_field_mask, file_google_protobuf_timestamp]);

/**
 * Describes the message admin.v1.Faculty.
 * Use `create(FacultySchema)` to create a new message.
 */
export const FacultySchema = /*@__PURE__*/
  messageDesc(file_admin_v1_faculty, 0);

/**
 * Describes the message admin.v1.ListFacultiesRequest.
 * Use `create(ListFacultiesRequestSchema)` to create a new message.
 */
export const ListFacultiesRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_faculty, 1);

/**
 * Describes the message admin.v1.ListFacultiesResponse.
 * Use `create(ListFacultiesResponseSchema)` to create a new message.
 */
export const ListFacultiesResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_faculty, 2);

/**
 * Describes the message admin.v1.GetFacultyRequest.
 * Use `create(GetFacultyRequestSchema)` to create a new message.
 */
export const GetFacultyRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_faculty, 3);

/**
 * Describes the message admin.v1.GetFacultyResponse.
 * Use `create(GetFacultyResponseSchema)` to create a new message.
 */
export const GetFacultyResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_faculty, 4);

/**
 * Describes the message admin.v1.CreateFacultyRequest.
 * Use `create(CreateFacultyRequestSchema)` to create a new message.
 */
export const CreateFacultyRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_faculty, 5);

/**
 * Describes the message admin.v1.CreateFacultyResponse.
 * Use `create(CreateFacultyResponseSchema)` to create a new message.
 */
export const CreateFacultyResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_faculty, 6);

/**
 * Describes the message admin.v1.UpdateFacultyRequest.
 * Use `create(UpdateFacultyRequestSchema)` to create a new message.
 */
export const UpdateFacultyRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_faculty, 7);

/**
 * Describes the message admin.v1.UpdateFacultyResponse.
 * Use `create(UpdateFacultyResponseSchema)` to create a new message.
 */
export const UpdateFacultyResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_faculty, 8);

/**
 * Describes the message admin.v1.DeleteFacultyRequest.
 * Use `create(DeleteFacultyRequestSchema)` to create a new message.
 */
export const DeleteFacultyRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_faculty, 9);

/**
 * Describes the message admin.v1.DeleteFacultyResponse.
 * Use `create(DeleteFacultyResponseSchema)` to create a new message.
 */
export const DeleteFacultyResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_faculty, 10);

/**
 * @generated from service admin.v1.FacultyService
 */
export const FacultyService = /*@__PURE__*/
  serviceDesc(file_admin_v1_faculty, 0);

