// @generated by protoc-gen-es v2.16.0
// @generated from file admin/v1/faculty.proto (package admin.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { FieldMask, Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file admin/v1/faculty.proto.
 */
export declare const file_admin_v1_faculty: GenFile;

/**
 * @generated from message admin.v1.Faculty
 */
export declare type Faculty = Message<"admin.v1.Faculty"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string email = 3;
   */
  email: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 4;
   */
  createdAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 5;
   */
  updatedAt?: Timestamp | undefined;
};

/**
 * Describes the message admin.v1.Faculty.
 * Use `create(FacultySchema)` to create a new message.
 */
export declare const FacultySchema: GenMessage<Faculty>;

/**
 * @generated from message admin.v1.ListFacultiesRequest
 */
export declare type ListFacultiesRequest = Message<"admin.v1.ListFacultiesRequest"> & {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;
};

/**
 * Describes the message admin.v1.ListFacultiesRequest.
 * Use `create(ListFacultiesRequestSchema)` to create a new message.
 */
export declare const ListFacultiesRequestSchema: GenMessage<ListFacultiesRequest>;

/**
 * @generated from message admin.v1.ListFacultiesResponse
 */
export declare type ListFacultiesResponse = Message<"admin.v1.ListFacultiesResponse"> & {
  /**
   * @generated from field: repeated admin.v1.Faculty faculties = 1;
   */
  faculties: Faculty[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message admin.v1.ListFacultiesResponse.
 * Use `create(ListFacultiesResponseSchema)` to create a new message.
 */
export declare const ListFacultiesResponseSchema: GenMessage<ListFacultiesResponse>;

/**
 * @generated from message admin.v1.GetFacultyRequest
 */
export declare type GetFacultyRequest = Message<"admin.v1.GetFacultyRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message admin.v1.GetFacultyRequest.
 * Use `create(GetFacultyRequestSchema)` to create a new message.
 */
export declare const GetFacultyRequestSchema: GenMessage<GetFacultyRequest>;

/**
 * @generated from message admin.v1.GetFacultyResponse
 */
export declare type GetFacultyResponse = Message<"admin.v1.GetFacultyResponse"> & {
  /**
   * @generated from field: admin.v1.Faculty faculty = 1;
   */
  faculty?: Faculty | undefined;
};

/**
 * Describes the message admin.v1.GetFacultyResponse.
 * Use `create(GetFacultyResponseSchema)` to create a new message.
 */
export declare const GetFacultyResponseSchema: GenMessage<GetFacultyResponse>;

/**
 * @generated from message admin.v1.CreateFacultyRequest
 */
export declare type CreateFacultyRequest = Message<"admin.v1.CreateFacultyRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;
};

/**
 * Describes the message admin.v1.CreateFacultyRequest.
 * Use `create(CreateFacultyRequestSchema)` to create a new message.
 */
export declare const CreateFacultyRequestSchema: GenMessage<CreateFacultyRequest>;

/**
 * @generated from message admin.v1.CreateFacultyResponse
 */
export declare type CreateFacultyResponse = Message<"admin.v1.CreateFacultyResponse"> & {
  /**
   * @generated from field: admin.v1.Faculty faculty = 1;
   */
  faculty?: Faculty | undefined;
};

/**
 * Describes the message admin.v1.CreateFacultyResponse.
 * Use `create(CreateFacultyResponseSchema)` to create a new message.
 */
export declare const CreateFacultyResponseSchema: GenMessage<CreateFacultyResponse>;

/**
 * @generated from message admin.v1.UpdateFacultyRequest
 */
export declare type UpdateFacultyRequest = Message<"admin.v1.UpdateFacultyRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string email = 3;
   */
  email: string;

  /**
   * @generated from field: google.protobuf.FieldMask update_mask = 99;
   */
  updateMask?: FieldMask | undefined;
};

/**
 * Describes the message admin.v1.UpdateFacultyRequest.
 * Use `create(UpdateFacultyRequestSchema)` to create a new message.
 */
export declare const UpdateFacultyRequestSchema: GenMessage<UpdateFacultyRequest>;

/**
 * @generated from message admin.v1.UpdateFacultyResponse
 */
export declare type UpdateFacultyResponse = Message<"admin.v1.UpdateFacultyResponse"> & {
  /**
   * @generated from field: admin.v1.Faculty faculty = 1;
   */
  faculty?: Faculty | undefined;
};

/**
 * Describes the message admin.v1.UpdateFacultyResponse.
 * Use `create(UpdateFacultyResponseSchema)` to create a new message.
 */
export declare const UpdateFacultyResponseSchema: GenMessage<UpdateFacultyResponse>;

/**
 * @generated from message admin.v1.DeleteFacultyRequest
 */
export declare type DeleteFacultyRequest = Message<"admin.v1.DeleteFacultyRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message admin.v1.DeleteFacultyRequest.
 * Use `create(DeleteFacultyRequestSchema)` to create a new message.
 */
export declare const DeleteFacultyRequestSchema: GenMessage<DeleteFacultyRequest>;

/**
 * @generated from message admin.v1.DeleteFacultyResponse
 */
export declare type DeleteFacultyResponse = Message<"admin.v1.DeleteFacultyResponse"> & {
};

/**
 * Describes the message admin.v1.DeleteFacultyResponse.
 * Use `create(DeleteFacultyResponseSchema)` to create a new message.
 */
export declare const DeleteFacultyResponseSchema: GenMessage<DeleteFacultyResponse>;

/**
 * @generated from service admin.v1.FacultyService
 */
export declare const FacultyService: GenService<{
  /**
   * @generated from rpc admin.v1.FacultyService.ListFaculties
   */
  listFaculties: {
    methodKind: "unary";
    input: typeof ListFacultiesRequestSchema;
    output: typeof ListFacultiesResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.FacultyService.GetFaculty
   */
  getFaculty: {
    methodKind: "unary";
    input: typeof GetFacultyRequestSchema;
    output: typeof GetFacultyResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.FacultyService.CreateFaculty
   */
  createFaculty: {
    methodKind: "unary";
    input: typeof CreateFacultyRequestSchema;
    output: typeof CreateFacultyResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.FacultyService.UpdateFaculty
   */
  updateFaculty: {
    methodKind: "unary";
    input: typeof UpdateFacultyRequestSchema;
    output: typeof UpdateFacultyResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.FacultyService.DeleteFaculty
   */
  deleteFaculty: {
    methodKind: "unary";
    input: typeof DeleteFacultyRequestSchema;
    output: typeof DeleteFacultyResponseSchema;
  },
}>;

