// @generated by protoc-gen-es v2.16.0
// @generated from file admin/v1/faculty_room.proto (package admin.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file admin/v1/faculty_room.proto.
 */
export const file_admin_v1_faculty_room = /*@__PURE__*/
  fileDesc("ChthZG1pbi92MS9mYWN1bHR5X3Jvb20ucHJvdG8SCGFkbWluLnYxIqABCgtGYWN1bHR5Um9vbRISCgpmYWN1bHR5X2lkGAEgASgJEg8KB3Jvb21faWQYAiABKAkSDAoEeWVhchgDIAEoBRIuCgpjcmVhdGVkX2F0GAQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgp1cGRhdGVkX2F0GAUgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCJAChdMaXN0RmFjdWx0eVJvb21zUmVxdWVzdBIRCglwYWdlX3NpemUYASABKAUSEgoKcGFnZV90b2tlbhgCIAEoCSJhChhMaXN0RmFjdWx0eVJvb21zUmVzcG9uc2USLAoNZmFjdWx0eV9yb29tcxgBIAMoCzIVLmFkbWluLnYxLkZhY3VsdHlSb29tEhcKD25leHRfcGFnZV90b2tlbhgCIAEoCSJKChVHZXRGYWN1bHR5Um9vbVJlcXVlc3QSEgoKZmFjdWx0eV9pZBgBIAEoCRIPCgdyb29tX2lkGAIgASgJEgwKBHllYXIYAyABKAUiRQoWR2V0RmFjdWx0eVJvb21SZXNwb25zZRIrCgxmYWN1bHR5X3Jvb20YASABKAsyFS5hZG1pbi52MS5GYWN1bHR5Um9vbSJNChhDcmVhdGVGYWN1bHR5Um9vbVJlcXVlc3QSEgoKZmFjdWx0eV9pZBgBIAEoCRIPCgdyb29tX2lkGAIgASgJEgwKBHllYXIYAyABKAUiSAoZQ3JlYXRlRmFjdWx0eVJvb21SZXNwb25zZRIrCgxmYWN1bHR5X3Jvb20YASABKAsyFS5hZG1pbi52MS5GYWN1bHR5Um9vbSJNChhEZWxldGVGYWN1bHR5Um9vbVJlcXVlc3QSEgoKZmFjdWx0eV9pZBgBIAEoCRIPCgdyb29tX2lkGAIgASgJEgwKBHllYXIYAyABKAUiGwoZRGVsZXRlRmFjdWx0eVJvb21SZXNwb25zZTKAAwoSRmFjdWx0eVJvb21TZXJ2aWNlElkKEExpc3RGYWN1bHR5Um9vbXMSIS5hZG1pbi52MS5MaXN0RmFjdWx0eVJvb21zUmVxdWVzdBoiLmFkbWluLnYxLkxpc3RGYWN1bHR5Um9vbXNSZXNwb25zZRJTCg5HZXRGYWN1bHR5Um9vbRIfLmFkbWluLnYxLkdldEZhY3VsdHlSb29tUmVxdWVzdBogLmFkbWluLnYxLkdldEZhY3VsdHlSb29tUmVzcG9uc2USXAoRQ3JlYXRlRmFjdWx0eVJvb20SIi5hZG1pbi52MS5DcmVhdGVGYWN1bHR5Um9vbVJlcXVlc3QaIy5hZG1pbi52MS5DcmVhdGVGYWN1bHR5Um9vbVJlc3BvbnNlElwKEURlbGV0ZUZhY3VsdHlSb29tEiIuYWRtaW4udjEuRGVsZXRlRmFjdWx0eVJvb21SZXF1ZXN0GiMuYWRtaW4udjEuRGVsZXRlRmFjdWx0eVJvb21SZXNwb25zZWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * Describes the message admin.v1.FacultyRoom.
 * Use `create(FacultyRoomSchema)` to create a new message.
 */
export const FacultyRoomSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_faculty_room, 0);

/**
 * Describes the message admin.v1.ListFacultyRoomsRequest.
 * Use `create(ListFacultyRoomsRequestSchema)` to create a new message.
 */
export const ListFacultyRoomsRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_faculty_room, 1);

/**
 * Describes the message admin.v1.ListFacultyRoomsResponse.
 * Use `create(ListFacultyRoomsResponseSchema)` to create a new message.
 */
export const ListFacultyRoomsResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_faculty_room, 2);

/**
 * Describes the message admin.v1.GetFacultyRoomRequest.
 * Use `create(GetFacultyRoomRequestSchema)` to create a new message.
 */
export const GetFacultyRoomRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_faculty_room, 3);

/**
 * Describes the message admin.v1.GetFacultyRoomResponse.
 * Use `create(GetFacultyRoomResponseSchema)` to create a new message.
 */
export const GetFacultyRoomResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_faculty_room, 4);

/**
 * Describes the message admin.v1.CreateFacultyRoomRequest.
 * Use `create(CreateFacultyRoomRequestSchema)` to create a new message.
 */
export const CreateFacultyRoomRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_faculty_room, 5);

/**
 * Describes the message admin.v1.CreateFacultyRoomResponse.
 * Use `create(CreateFacultyRoomResponseSchema)` to create a new message.
 */
export const CreateFacultyRoomResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_faculty_room, 6);

/**
 * Describes the message admin.v1.DeleteFacultyRoomRequest.
 * Use `create(DeleteFacultyRoomRequestSchema)` to create a new message.
 */
export const DeleteFacultyRoomRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_faculty_room, 7);

/**
 * Describes the message admin.v1.DeleteFacultyRoomResponse.
 * Use `create(DeleteFacultyRoomResponseSchema)` to create a new message.
 */
export const DeleteFacultyRoomResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_faculty_room, 8);

/**
 * @generated from service admin.v1.FacultyRoomService
 */
export const FacultyRoomService = /*@__PURE__*/
  serviceDesc(file_admin_v1_faculty_room, 0);

