// @generated by protoc-gen-es v2.16.0
// @generated from file admin/v1/fcm_token.proto (package admin.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_field_mask, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file admin/v1/fcm_token.proto.
 */
export const file_admin_v1_fcm_token = /*@__PURE__*/
  fileDesc("ChhhZG1pbi92MS9mY21fdG9rZW4ucHJvdG8SCGFkbWluLnYxIooBCghGY21Ub2tlbhINCgV0b2tlbhgBIAEoCRIPCgd1c2VyX2lkGAIgASgJEi4KCmNyZWF0ZWRfYXQYAyABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4KCnVwZGF0ZWRfYXQYBCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wIj0KFExpc3RGY21Ub2tlbnNSZXF1ZXN0EhEKCXBhZ2Vfc2l6ZRgBIAEoBRISCgpwYWdlX3Rva2VuGAIgASgJIlgKFUxpc3RGY21Ub2tlbnNSZXNwb25zZRImCgpmY21fdG9rZW5zGAEgAygLMhIuYWRtaW4udjEuRmNtVG9rZW4SFwoPbmV4dF9wYWdlX3Rva2VuGAIgASgJIiMKEkdldEZjbVRva2VuUmVxdWVzdBINCgV0b2tlbhgBIAEoCSI8ChNHZXRGY21Ub2tlblJlc3BvbnNlEiUKCWZjbV90b2tlbhgBIAEoCzISLmFkbWluLnYxLkZjbVRva2VuIjcKFUNyZWF0ZUZjbVRva2VuUmVxdWVzdBINCgV0b2tlbhgBIAEoCRIPCgd1c2VyX2lkGAIgASgJIj8KFkNyZWF0ZUZjbVRva2VuUmVzcG9uc2USJQoJZmNtX3Rva2VuGAEgASgLMhIuYWRtaW4udjEuRmNtVG9rZW4iaAoVVXBkYXRlRmNtVG9rZW5SZXF1ZXN0Eg0KBXRva2VuGAEgASgJEg8KB3VzZXJfaWQYAiABKAkSLwoLdXBkYXRlX21hc2sYYyABKAsyGi5nb29nbGUucHJvdG9idWYuRmllbGRNYXNrIj8KFlVwZGF0ZUZjbVRva2VuUmVzcG9uc2USJQoJZmNtX3Rva2VuGAEgASgLMhIuYWRtaW4udjEuRmNtVG9rZW4iJgoVRGVsZXRlRmNtVG9rZW5SZXF1ZXN0Eg0KBXRva2VuGAEgASgJIhgKFkRlbGV0ZUZjbVRva2VuUmVzcG9uc2UyrgMKD0ZjbVRva2VuU2VydmljZRJQCg1MaXN0RmNtVG9rZW5zEh4uYWRtaW4udjEuTGlzdEZjbVRva2Vuc1JlcXVlc3QaHy5hZG1pbi52MS5MaXN0RmNtVG9rZW5zUmVzcG9uc2USSgoLR2V0RmNtVG9rZW4SHC5hZG1pbi52MS5HZXRGY21Ub2tlblJlcXVlc3QaHS5hZG1pbi52MS5HZXRGY21Ub2tlblJlc3BvbnNlElMKDkNyZWF0ZUZjbVRva2VuEh8uYWRtaW4udjEuQ3JlYXRlRmNtVG9rZW5SZXF1ZXN0GiAuYWRtaW4udjEuQ3JlYXRlRmNtVG9rZW5SZXNwb25zZRJTCg5VcGRhdGVGY21Ub2tlbhIfLmFkbWluLnYxLlVwZGF0ZUZjbVRva2VuUmVxdWVzdBogLmFkbWluLnYxLlVwZGF0ZUZjbVRva2VuUmVzcG9uc2USUwoORGVsZXRlRmNtVG9rZW4SHy5hZG1pbi52MS5EZWxldGVGY21Ub2tlblJlcXVlc3QaIC5hZG1pbi52MS5EZWxldGVGY21Ub2tlblJlc3BvbnNlYgZwcm90bzM", [file_google_protobuf_field_mask, file_google_protobuf_timestamp]);

/**
 * Describes the message admin.v1.FcmToken.
 * Use `create(FcmTokenSchema)` to create a new message.
 */
export const FcmTokenSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_fcm_token, 0);

/**
 * Describes the message admin.v1.ListFcmTokensRequest.
 * Use `create(ListFcmTokensRequestSchema)` to create a new message.
 */
export const ListFcmTokensRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_fcm_token, 1);

/**
 * Describes the message admin.v1.ListFcmTokensResponse.
 * Use `create(ListFcmTokensResponseSchema)` to create a new message.
 */
export const ListFcmTokensResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_fcm_token, 2);

/**
 * Describes the message admin.v1.GetFcmTokenRequest.
 * Use `create(GetFcmTokenRequestSchema)` to create a new message.
 */
export const GetFcmTokenRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_fcm_token, 3);

/**
 * Describes the message admin.v1.GetFcmTokenResponse.
 * Use `create(GetFcmTokenResponseSchema)` to create a new message.
 */
export const GetFcmTokenResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_fcm_token, 4);

/**
 * Describes the message admin.v1.CreateFcmTokenRequest.
 * Use `create(CreateFcmTokenRequestSchema)` to create a new message.
 */
export const CreateFcmTokenRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_fcm_token, 5);

/**
 * Describes the message admin.v1.CreateFcmTokenResponse.
 * Use `create(CreateFcmTokenResponseSchema)` to create a new message.
 */
export const CreateFcmTokenResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_fcm_token, 6);

/**
 * Describes the message admin.v1.UpdateFcmTokenRequest.
 * Use `create(UpdateFcmTokenRequestSchema)` to create a new message.
 */
export const UpdateFcmTokenRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_fcm_token, 7);

/**
 * Describes the message admin.v1.UpdateFcmTokenResponse.
 * Use `create(UpdateFcmTokenResponseSchema)` to create a new message.
 */
export const UpdateFcmTokenResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_fcm_token, 8);

/**
 * Describes the message admin.v1.DeleteFcmTokenRequest.
 * Use `create(DeleteFcmTokenRequestSchema)` to create a new message.
 */
export const DeleteFcmTokenRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_fcm_token, 9);

/**
 * Describes the message admin.v1.DeleteFcmTokenResponse.
 * Use `create(DeleteFcmTokenResponseSchema)` to create a new message.
 */
export const DeleteFcmTokenResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_fcm_token, 10);

/**
 * @generated from service admin.v1.FcmTokenService
 */
export const FcmTokenService = /*@__PURE__*/
  serviceDesc(file_admin_v1_fcm_token, 0);

