// @generated by protoc-gen-es v2.16.0
// @generated from file admin/v1/makeup_class.proto (package admin.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Date } from "../../google/type/date_pb";
import type { Period } from "./common_pb";
import type { FieldMask, Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file admin/v1/makeup_class.proto.
 */
export declare const file_admin_v1_makeup_class: GenFile;

/**
 * @generated from message admin.v1.MakeupClass
 */
export declare type MakeupClass = Message<"admin.v1.MakeupClass"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string subject_id = 2;
   */
  subjectId: string;

  /**
   * @generated from field: google.type.Date date = 3;
   */
  date?: Date | undefined;

  /**
   * @generated from field: admin.v1.Period period = 4;
   */
  period: Period;

  /**
   * @generated from field: optional string comment = 5;
   */
  comment?: string | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 6;
   */
  createdAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 7;
   */
  updatedAt?: Timestamp | undefined;
};

/**
 * Describes the message admin.v1.MakeupClass.
 * Use `create(MakeupClassSchema)` to create a new message.
 */
export declare const MakeupClassSchema: GenMessage<MakeupClass>;

/**
 * @generated from message admin.v1.ListMakeupClassesRequest
 */
export declare type ListMakeupClassesRequest = Message<"admin.v1.ListMakeupClassesRequest"> & {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;
};

/**
 * Describes the message admin.v1.ListMakeupClassesRequest.
 * Use `create(ListMakeupClassesRequestSchema)` to create a new message.
 */
export declare const ListMakeupClassesRequestSchema: GenMessage<ListMakeupClassesRequest>;

/**
 * @generated from message admin.v1.ListMakeupClassesResponse
 */
export declare type ListMakeupClassesResponse = Message<"admin.v1.ListMakeupClassesResponse"> & {
  /**
   * @generated from field: repeated admin.v1.MakeupClass makeup_classes = 1;
   */
  makeupClasses: MakeupClass[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message admin.v1.ListMakeupClassesResponse.
 * Use `create(ListMakeupClassesResponseSchema)` to create a new message.
 */
export declare const ListMakeupClassesResponseSchema: GenMessage<ListMakeupClassesResponse>;

/**
 * @generated from message admin.v1.GetMakeupClassRequest
 */
export declare type GetMakeupClassRequest = Message<"admin.v1.GetMakeupClassRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message admin.v1.GetMakeupClassRequest.
 * Use `create(GetMakeupClassRequestSchema)` to create a new message.
 */
export declare const GetMakeupClassRequestSchema: GenMessage<GetMakeupClassRequest>;

/**
 * @generated from message admin.v1.GetMakeupClassResponse
 */
export declare type GetMakeupClassResponse = Message<"admin.v1.GetMakeupClassResponse"> & {
  /**
   * @generated from field: admin.v1.MakeupClass makeup_class = 1;
   */
  makeupClass?: MakeupClass | undefined;
};

/**
 * Describes the message admin.v1.GetMakeupClassResponse.
 * Use `create(GetMakeupClassResponseSchema)` to create a new message.
 */
export declare const GetMakeupClassResponseSchema: GenMessage<GetMakeupClassResponse>;

/**
 * @generated from message admin.v1.CreateMakeupClassRequest
 */
export declare type CreateMakeupClassRequest = Message<"admin.v1.CreateMakeupClassRequest"> & {
  /**
   * @generated from field: string subject_id = 1;
   */
  subjectId: string;

  /**
   * @generated from field: google.type.Date date = 2;
   */
  date?: Date | undefined;

  /**
   * @generated from field: admin.v1.Period period = 3;
   */
  period: Period;

  /**
   * @generated from field: optional string comment = 4;
   */
  comment?: string | undefined;
};

/**
 * Describes the message admin.v1.CreateMakeupClassRequest.
 * Use `create(CreateMakeupClassRequestSchema)` to create a new message.
 */
export declare const CreateMakeupClassRequestSchema: GenMessage<CreateMakeupClassRequest>;

/**
 * @generated from message admin.v1.CreateMakeupClassResponse
 */
export declare type CreateMakeupClassResponse = Message<"admin.v1.CreateMakeupClassResponse"> & {
  /**
   * @generated from field: admin.v1.MakeupClass makeup_class = 1;
   */
  makeupClass?: MakeupClass | undefined;
};

/**
 * Describes the message admin.v1.CreateMakeupClassResponse.
 * Use `create(CreateMakeupClassResponseSchema)` to create a new message.
 */
export declare const CreateMakeupClassResponseSchema: GenMessage<CreateMakeupClassResponse>;

/**
 * @generated from message admin.v1.UpdateMakeupClassRequest
 */
export declare type UpdateMakeupClassRequest = Message<"admin.v1.UpdateMakeupClassRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string subject_id = 2;
   */
  subjectId: string;

  /**
   * @generated from field: google.type.Date date = 3;
   */
  date?: Date | undefined;

  /**
   * @generated from field: admin.v1.Period period = 4;
   */
  period: Period;

  /**
   * @generated from field: optional string comment = 5;
   */
  comment?: string | undefined;

  /**
   * @generated from field: google.protobuf.FieldMask update_mask = 99;
   */
  updateMask?: FieldMask | undefined;
};

/**
 * Describes the message admin.v1.UpdateMakeupClassRequest.
 * Use `create(UpdateMakeupClassRequestSchema)` to create a new message.
 */
export declare const UpdateMakeupClassRequestSchema: GenMessage<UpdateMakeupClassRequest>;

/**
 * @generated from message admin.v1.UpdateMakeupClassResponse
 */
export declare type UpdateMakeupClassResponse = Message<"admin.v1.UpdateMakeupClassResponse"> & {
  /**
   * @generated from field: admin.v1.MakeupClass makeup_class = 1;
   */
  makeupClass?: MakeupClass | undefined;
};

/**
 * Describes the message admin.v1.UpdateMakeupClassResponse.
 * Use `create(UpdateMakeupClassResponseSchema)` to create a new message.
 */
export declare const UpdateMakeupClassResponseSchema: GenMessage<UpdateMakeupClassResponse>;

/**
 * @generated from message admin.v1.DeleteMakeupClassRequest
 */
export declare type DeleteMakeupClassRequest = Message<"admin.v1.DeleteMakeupClassRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message admin.v1.DeleteMakeupClassRequest.
 * Use `create(DeleteMakeupClassRequestSchema)` to create a new message.
 */
export declare const DeleteMakeupClassRequestSchema: GenMessage<DeleteMakeupClassRequest>;

/**
 * @generated from message admin.v1.DeleteMakeupClassResponse
 */
export declare type DeleteMakeupClassResponse = Message<"admin.v1.DeleteMakeupClassResponse"> & {
};

/**
 * Describes the message admin.v1.DeleteMakeupClassResponse.
 * Use `create(DeleteMakeupClassResponseSchema)` to create a new message.
 */
export declare const DeleteMakeupClassResponseSchema: GenMessage<DeleteMakeupClassResponse>;

/**
 * @generated from service admin.v1.MakeupClassService
 */
export declare const MakeupClassService: GenService<{
  /**
   * @generated from rpc admin.v1.MakeupClassService.ListMakeupClasses
   */
  listMakeupClasses: {
    methodKind: "unary";
    input: typeof ListMakeupClassesRequestSchema;
    output: typeof ListMakeupClassesResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.MakeupClassService.GetMakeupClass
   */
  getMakeupClass: {
    methodKind: "unary";
    input: typeof GetMakeupClassRequestSchema;
    output: typeof GetMakeupClassResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.MakeupClassService.CreateMakeupClass
   */
  createMakeupClass: {
    methodKind: "unary";
    input: typeof CreateMakeupClassRequestSchema;
    output: typeof CreateMakeupClassResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.MakeupClassService.UpdateMakeupClass
   */
  updateMakeupClass: {
    methodKind: "unary";
    input: typeof UpdateMakeupClassRequestSchema;
    output: typeof UpdateMakeupClassResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.MakeupClassService.DeleteMakeupClass
   */
  deleteMakeupClass: {
    methodKind: "unary";
    input: typeof DeleteMakeupClassRequestSchema;
    output: typeof DeleteMakeupClassResponseSchema;
  },
}>;

