// @generated by protoc-gen-es v2.16.0
// @generated from file admin/v1/notification.proto (package admin.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { FieldMask, Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file admin/v1/notification.proto.
 */
export declare const file_admin_v1_notification: GenFile;

/**
 * @generated from message admin.v1.Notification
 */
export declare type Notification = Message<"admin.v1.Notification"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string body = 3;
   */
  body: string;

  /**
   * @generated from field: optional string image_url = 4;
   */
  imageUrl?: string | undefined;

  /**
   * @generated from field: optional string analytics_label = 5;
   */
  analyticsLabel?: string | undefined;

  /**
   * @generated from field: optional int32 apns_badge = 6;
   */
  apnsBadge?: number | undefined;

  /**
   * @generated from field: optional string apns_sound = 7;
   */
  apnsSound?: string | undefined;

  /**
   * @generated from field: optional bool apns_content_available = 8;
   */
  apnsContentAvailable?: boolean | undefined;

  /**
   * @generated from field: optional string android_channel_id = 9;
   */
  androidChannelId?: string | undefined;

  /**
   * @generated from field: optional admin.v1.NotificationAndroidPriority android_priority = 10;
   */
  androidPriority?: NotificationAndroidPriority | undefined;

  /**
   * @generated from field: optional int32 android_ttl_seconds = 11;
   */
  androidTtlSeconds?: number | undefined;

  /**
   * @generated from field: optional string webpush_link = 12;
   */
  webpushLink?: string | undefined;

  /**
   * @generated from field: optional string url = 13;
   */
  url?: string | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp notify_after = 14;
   */
  notifyAfter?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp notify_before = 15;
   */
  notifyBefore?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 16;
   */
  createdAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 17;
   */
  updatedAt?: Timestamp | undefined;
};

/**
 * Describes the message admin.v1.Notification.
 * Use `create(NotificationSchema)` to create a new message.
 */
export declare const NotificationSchema: GenMessage<Notification>;

/**
 * @generated from message admin.v1.ListNotificationsRequest
 */
export declare type ListNotificationsRequest = Message<"admin.v1.ListNotificationsRequest"> & {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;
};

/**
 * Describes the message admin.v1.ListNotificationsRequest.
 * Use `create(ListNotificationsRequestSchema)` to create a new message.
 */
export declare const ListNotificationsRequestSchema: GenMessage<ListNotificationsRequest>;

/**
 * @generated from message admin.v1.ListNotificationsResponse
 */
export declare type ListNotificationsResponse = Message<"admin.v1.ListNotificationsResponse"> & {
  /**
   * @generated from field: repeated admin.v1.Notification notifications = 1;
   */
  notifications: Notification[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message admin.v1.ListNotificationsResponse.
 * Use `create(ListNotificationsResponseSchema)` to create a new message.
 */
export declare const ListNotificationsResponseSchema: GenMessage<ListNotificationsResponse>;

/**
 * @generated from message admin.v1.GetNotificationRequest
 */
export declare type GetNotificationRequest = Message<"admin.v1.GetNotificationRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message admin.v1.GetNotificationRequest.
 * Use `create(GetNotificationRequestSchema)` to create a new message.
 */
export declare const GetNotificationRequestSchema: GenMessage<GetNotificationRequest>;

/**
 * @generated from message admin.v1.GetNotificationResponse
 */
export declare type GetNotificationResponse = Message<"admin.v1.GetNotificationResponse"> & {
  /**
   * @generated from field: admin.v1.Notification notification = 1;
   */
  notification?: Notification | undefined;
};

/**
 * Describes the message admin.v1.GetNotificationResponse.
 * Use `create(GetNotificationResponseSchema)` to create a new message.
 */
export declare const GetNotificationResponseSchema: GenMessage<GetNotificationResponse>;

/**
 * @generated from message admin.v1.CreateNotificationRequest
 */
export declare type CreateNotificationRequest = Message<"admin.v1.CreateNotificationRequest"> & {
  /**
   * @generated from field: string title = 1;
   */
  title: string;

  /**
   * @generated from field: string body = 2;
   */
  body: string;

  /**
   * @generated from field: optional string image_url = 3;
   */
  imageUrl?: string | undefined;

  /**
   * @generated from field: optional string analytics_label = 4;
   */
  analyticsLabel?: string | undefined;

  /**
   * @generated from field: optional int32 apns_badge = 5;
   */
  apnsBadge?: number | undefined;

  /**
   * @generated from field: optional string apns_sound = 6;
   */
  apnsSound?: string | undefined;

  /**
   * @generated from field: optional bool apns_content_available = 7;
   */
  apnsContentAvailable?: boolean | undefined;

  /**
   * @generated from field: optional string android_channel_id = 8;
   */
  androidChannelId?: string | undefined;

  /**
   * @generated from field: optional admin.v1.NotificationAndroidPriority android_priority = 9;
   */
  androidPriority?: NotificationAndroidPriority | undefined;

  /**
   * @generated from field: optional int32 android_ttl_seconds = 10;
   */
  androidTtlSeconds?: number | undefined;

  /**
   * @generated from field: optional string webpush_link = 11;
   */
  webpushLink?: string | undefined;

  /**
   * @generated from field: optional string url = 12;
   */
  url?: string | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp notify_after = 13;
   */
  notifyAfter?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp notify_before = 14;
   */
  notifyBefore?: Timestamp | undefined;
};

/**
 * Describes the message admin.v1.CreateNotificationRequest.
 * Use `create(CreateNotificationRequestSchema)` to create a new message.
 */
export declare const CreateNotificationRequestSchema: GenMessage<CreateNotificationRequest>;

/**
 * @generated from message admin.v1.CreateNotificationResponse
 */
export declare type CreateNotificationResponse = Message<"admin.v1.CreateNotificationResponse"> & {
  /**
   * @generated from field: admin.v1.Notification notification = 1;
   */
  notification?: Notification | undefined;
};

/**
 * Describes the message admin.v1.CreateNotificationResponse.
 * Use `create(CreateNotificationResponseSchema)` to create a new message.
 */
export declare const CreateNotificationResponseSchema: GenMessage<CreateNotificationResponse>;

/**
 * @generated from message admin.v1.UpdateNotificationRequest
 */
export declare type UpdateNotificationRequest = Message<"admin.v1.UpdateNotificationRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string body = 3;
   */
  body: string;

  /**
   * @generated from field: optional string image_url = 4;
   */
  imageUrl?: string | undefined;

  /**
   * @generated from field: optional string analytics_label = 5;
   */
  analyticsLabel?: string | undefined;

  /**
   * @generated from field: optional int32 apns_badge = 6;
   */
  apnsBadge?: number | undefined;

  /**
   * @generated from field: optional string apns_sound = 7;
   */
  apnsSound?: string | undefined;

  /**
   * @generated from field: optional bool apns_content_available = 8;
   */
  apnsContentAvailable?: boolean | undefined;

  /**
   * @generated from field: optional string android_channel_id = 9;
   */
  androidChannelId?: string | undefined;

  /**
   * @generated from field: optional admin.v1.NotificationAndroidPriority android_priority = 10;
   */
  androidPriority?: NotificationAndroidPriority | undefined;

  /**
   * @generated from field: optional int32 android_ttl_seconds = 11;
   */
  androidTtlSeconds?: number | undefined;

  /**
   * @generated from field: optional string webpush_link = 12;
   */
  webpushLink?: string | undefined;

  /**
   * @generated from field: optional string url = 13;
   */
  url?: string | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp notify_after = 14;
   */
  notifyAfter?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp notify_before = 15;
   */
  notifyBefore?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.FieldMask update_mask = 99;
   */
  updateMask?: FieldMask | undefined;
};

/**
 * Describes the message admin.v1.UpdateNotificationRequest.
 * Use `create(UpdateNotificationRequestSchema)` to create a new message.
 */
export declare const UpdateNotificationRequestSchema: GenMessage<UpdateNotificationRequest>;

/**
 * @generated from message admin.v1.UpdateNotificationResponse
 */
export declare type UpdateNotificationResponse = Message<"admin.v1.UpdateNotificationResponse"> & {
  /**
   * @generated from field: admin.v1.Notification notification = 1;
   */
  notification?: Notification | undefined;
};

/**
 * Describes the message admin.v1.UpdateNotificationResponse.
 * Use `create(UpdateNotificationResponseSchema)` to create a new message.
 */
export declare const UpdateNotificationResponseSchema: GenMessage<UpdateNotificationResponse>;

/**
 * @generated from message admin.v1.DeleteNotificationRequest
 */
export declare type DeleteNotificationRequest = Message<"admin.v1.DeleteNotificationRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message admin.v1.DeleteNotificationRequest.
 * Use `create(DeleteNotificationRequestSchema)` to create a new message.
 */
export declare const DeleteNotificationRequestSchema: GenMessage<DeleteNotificationRequest>;

/**
 * @generated from message admin.v1.DeleteNotificationResponse
 */
export declare type DeleteNotificationResponse = Message<"admin.v1.DeleteNotificationResponse"> & {
};

/**
 * Describes the message admin.v1.DeleteNotificationResponse.
 * Use `create(DeleteNotificationResponseSchema)` to create a new message.
 */
export declare const DeleteNotificationResponseSchema: GenMessage<DeleteNotificationResponse>;

/**
 * @generated from enum admin.v1.NotificationAndroidPriority
 */
export enum NotificationAndroidPriority {
  /**
   * @generated from enum value: NOTIFICATION_ANDROID_PRIORITY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: NOTIFICATION_ANDROID_PRIORITY_NORMAL = 1;
   */
  NORMAL = 1,

  /**
   * @generated from enum value: NOTIFICATION_ANDROID_PRIORITY_HIGH = 2;
   */
  HIGH = 2,
}

/**
 * Describes the enum admin.v1.NotificationAndroidPriority.
 */
export declare const NotificationAndroidPrioritySchema: GenEnum<NotificationAndroidPriority>;

/**
 * @generated from service admin.v1.NotificationService
 */
export declare const NotificationService: GenService<{
  /**
   * @generated from rpc admin.v1.NotificationService.ListNotifications
   */
  listNotifications: {
    methodKind: "unary";
    input: typeof ListNotificationsRequestSchema;
    output: typeof ListNotificationsResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.NotificationService.GetNotification
   */
  getNotification: {
    methodKind: "unary";
    input: typeof GetNotificationRequestSchema;
    output: typeof GetNotificationResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.NotificationService.CreateNotification
   */
  createNotification: {
    methodKind: "unary";
    input: typeof CreateNotificationRequestSchema;
    output: typeof CreateNotificationResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.NotificationService.UpdateNotification
   */
  updateNotification: {
    methodKind: "unary";
    input: typeof UpdateNotificationRequestSchema;
    output: typeof UpdateNotificationResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.NotificationService.DeleteNotification
   */
  deleteNotification: {
    methodKind: "unary";
    input: typeof DeleteNotificationRequestSchema;
    output: typeof DeleteNotificationResponseSchema;
  },
}>;

