// @generated by protoc-gen-es v2.16.0
// @generated from file admin/v1/room_reservation.proto (package admin.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { FieldMask, Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file admin/v1/room_reservation.proto.
 */
export declare const file_admin_v1_room_reservation: GenFile;

/**
 * @generated from message admin.v1.RoomReservation
 */
export declare type RoomReservation = Message<"admin.v1.RoomReservation"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string room_id = 3;
   */
  roomId: string;

  /**
   * @generated from field: google.protobuf.Timestamp start_time = 4;
   */
  startTime?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp end_time = 5;
   */
  endTime?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 6;
   */
  createdAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 7;
   */
  updatedAt?: Timestamp | undefined;
};

/**
 * Describes the message admin.v1.RoomReservation.
 * Use `create(RoomReservationSchema)` to create a new message.
 */
export declare const RoomReservationSchema: GenMessage<RoomReservation>;

/**
 * @generated from message admin.v1.ListRoomReservationsRequest
 */
export declare type ListRoomReservationsRequest = Message<"admin.v1.ListRoomReservationsRequest"> & {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;
};

/**
 * Describes the message admin.v1.ListRoomReservationsRequest.
 * Use `create(ListRoomReservationsRequestSchema)` to create a new message.
 */
export declare const ListRoomReservationsRequestSchema: GenMessage<ListRoomReservationsRequest>;

/**
 * @generated from message admin.v1.ListRoomReservationsResponse
 */
export declare type ListRoomReservationsResponse = Message<"admin.v1.ListRoomReservationsResponse"> & {
  /**
   * @generated from field: repeated admin.v1.RoomReservation room_reservations = 1;
   */
  roomReservations: RoomReservation[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message admin.v1.ListRoomReservationsResponse.
 * Use `create(ListRoomReservationsResponseSchema)` to create a new message.
 */
export declare const ListRoomReservationsResponseSchema: GenMessage<ListRoomReservationsResponse>;

/**
 * @generated from message admin.v1.GetRoomReservationRequest
 */
export declare type GetRoomReservationRequest = Message<"admin.v1.GetRoomReservationRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message admin.v1.GetRoomReservationRequest.
 * Use `create(GetRoomReservationRequestSchema)` to create a new message.
 */
export declare const GetRoomReservationRequestSchema: GenMessage<GetRoomReservationRequest>;

/**
 * @generated from message admin.v1.GetRoomReservationResponse
 */
export declare type GetRoomReservationResponse = Message<"admin.v1.GetRoomReservationResponse"> & {
  /**
   * @generated from field: admin.v1.RoomReservation room_reservation = 1;
   */
  roomReservation?: RoomReservation | undefined;
};

/**
 * Describes the message admin.v1.GetRoomReservationResponse.
 * Use `create(GetRoomReservationResponseSchema)` to create a new message.
 */
export declare const GetRoomReservationResponseSchema: GenMessage<GetRoomReservationResponse>;

/**
 * @generated from message admin.v1.CreateRoomReservationRequest
 */
export declare type CreateRoomReservationRequest = Message<"admin.v1.CreateRoomReservationRequest"> & {
  /**
   * @generated from field: string title = 1;
   */
  title: string;

  /**
   * @generated from field: string room_id = 2;
   */
  roomId: string;

  /**
   * @generated from field: google.protobuf.Timestamp start_time = 3;
   */
  startTime?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp end_time = 4;
   */
  endTime?: Timestamp | undefined;
};

/**
 * Describes the message admin.v1.CreateRoomReservationRequest.
 * Use `create(CreateRoomReservationRequestSchema)` to create a new message.
 */
export declare const CreateRoomReservationRequestSchema: GenMessage<CreateRoomReservationRequest>;

/**
 * @generated from message admin.v1.CreateRoomReservationResponse
 */
export declare type CreateRoomReservationResponse = Message<"admin.v1.CreateRoomReservationResponse"> & {
  /**
   * @generated from field: admin.v1.RoomReservation room_reservation = 1;
   */
  roomReservation?: RoomReservation | undefined;
};

/**
 * Describes the message admin.v1.CreateRoomReservationResponse.
 * Use `create(CreateRoomReservationResponseSchema)` to create a new message.
 */
export declare const CreateRoomReservationResponseSchema: GenMessage<CreateRoomReservationResponse>;

/**
 * @generated from message admin.v1.UpdateRoomReservationRequest
 */
export declare type UpdateRoomReservationRequest = Message<"admin.v1.UpdateRoomReservationRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string room_id = 3;
   */
  roomId: string;

  /**
   * @generated from field: google.protobuf.Timestamp start_time = 4;
   */
  startTime?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp end_time = 5;
   */
  endTime?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.FieldMask update_mask = 99;
   */
  updateMask?: FieldMask | undefined;
};

/**
 * Describes the message admin.v1.UpdateRoomReservationRequest.
 * Use `create(UpdateRoomReservationRequestSchema)` to create a new message.
 */
export declare const UpdateRoomReservationRequestSchema: GenMessage<UpdateRoomReservationRequest>;

/**
 * @generated from message admin.v1.UpdateRoomReservationResponse
 */
export declare type UpdateRoomReservationResponse = Message<"admin.v1.UpdateRoomReservationResponse"> & {
  /**
   * @generated from field: admin.v1.RoomReservation room_reservation = 1;
   */
  roomReservation?: RoomReservation | undefined;
};

/**
 * Describes the message admin.v1.UpdateRoomReservationResponse.
 * Use `create(UpdateRoomReservationResponseSchema)` to create a new message.
 */
export declare const UpdateRoomReservationResponseSchema: GenMessage<UpdateRoomReservationResponse>;

/**
 * @generated from message admin.v1.DeleteRoomReservationRequest
 */
export declare type DeleteRoomReservationRequest = Message<"admin.v1.DeleteRoomReservationRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message admin.v1.DeleteRoomReservationRequest.
 * Use `create(DeleteRoomReservationRequestSchema)` to create a new message.
 */
export declare const DeleteRoomReservationRequestSchema: GenMessage<DeleteRoomReservationRequest>;

/**
 * @generated from message admin.v1.DeleteRoomReservationResponse
 */
export declare type DeleteRoomReservationResponse = Message<"admin.v1.DeleteRoomReservationResponse"> & {
};

/**
 * Describes the message admin.v1.DeleteRoomReservationResponse.
 * Use `create(DeleteRoomReservationResponseSchema)` to create a new message.
 */
export declare const DeleteRoomReservationResponseSchema: GenMessage<DeleteRoomReservationResponse>;

/**
 * @generated from service admin.v1.RoomReservationService
 */
export declare const RoomReservationService: GenService<{
  /**
   * @generated from rpc admin.v1.RoomReservationService.ListRoomReservations
   */
  listRoomReservations: {
    methodKind: "unary";
    input: typeof ListRoomReservationsRequestSchema;
    output: typeof ListRoomReservationsResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.RoomReservationService.GetRoomReservation
   */
  getRoomReservation: {
    methodKind: "unary";
    input: typeof GetRoomReservationRequestSchema;
    output: typeof GetRoomReservationResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.RoomReservationService.CreateRoomReservation
   */
  createRoomReservation: {
    methodKind: "unary";
    input: typeof CreateRoomReservationRequestSchema;
    output: typeof CreateRoomReservationResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.RoomReservationService.UpdateRoomReservation
   */
  updateRoomReservation: {
    methodKind: "unary";
    input: typeof UpdateRoomReservationRequestSchema;
    output: typeof UpdateRoomReservationResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.RoomReservationService.DeleteRoomReservation
   */
  deleteRoomReservation: {
    methodKind: "unary";
    input: typeof DeleteRoomReservationRequestSchema;
    output: typeof DeleteRoomReservationResponseSchema;
  },
}>;

