// @generated by protoc-gen-es v2.16.0
// @generated from file admin/v1/room_change.proto (package admin.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Date } from "../../google/type/date_pb";
import type { Period } from "./common_pb";
import type { FieldMask, Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file admin/v1/room_change.proto.
 */
export declare const file_admin_v1_room_change: GenFile;

/**
 * @generated from message admin.v1.RoomChange
 */
export declare type RoomChange = Message<"admin.v1.RoomChange"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string subject_id = 2;
   */
  subjectId: string;

  /**
   * @generated from field: google.type.Date date = 3;
   */
  date?: Date | undefined;

  /**
   * @generated from field: admin.v1.Period period = 4;
   */
  period: Period;

  /**
   * @generated from field: string original_room_id = 5;
   */
  originalRoomId: string;

  /**
   * @generated from field: string new_room_id = 6;
   */
  newRoomId: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 7;
   */
  createdAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 8;
   */
  updatedAt?: Timestamp | undefined;
};

/**
 * Describes the message admin.v1.RoomChange.
 * Use `create(RoomChangeSchema)` to create a new message.
 */
export declare const RoomChangeSchema: GenMessage<RoomChange>;

/**
 * @generated from message admin.v1.ListRoomChangesRequest
 */
export declare type ListRoomChangesRequest = Message<"admin.v1.ListRoomChangesRequest"> & {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;
};

/**
 * Describes the message admin.v1.ListRoomChangesRequest.
 * Use `create(ListRoomChangesRequestSchema)` to create a new message.
 */
export declare const ListRoomChangesRequestSchema: GenMessage<ListRoomChangesRequest>;

/**
 * @generated from message admin.v1.ListRoomChangesResponse
 */
export declare type ListRoomChangesResponse = Message<"admin.v1.ListRoomChangesResponse"> & {
  /**
   * @generated from field: repeated admin.v1.RoomChange room_changes = 1;
   */
  roomChanges: RoomChange[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message admin.v1.ListRoomChangesResponse.
 * Use `create(ListRoomChangesResponseSchema)` to create a new message.
 */
export declare const ListRoomChangesResponseSchema: GenMessage<ListRoomChangesResponse>;

/**
 * @generated from message admin.v1.GetRoomChangeRequest
 */
export declare type GetRoomChangeRequest = Message<"admin.v1.GetRoomChangeRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message admin.v1.GetRoomChangeRequest.
 * Use `create(GetRoomChangeRequestSchema)` to create a new message.
 */
export declare const GetRoomChangeRequestSchema: GenMessage<GetRoomChangeRequest>;

/**
 * @generated from message admin.v1.GetRoomChangeResponse
 */
export declare type GetRoomChangeResponse = Message<"admin.v1.GetRoomChangeResponse"> & {
  /**
   * @generated from field: admin.v1.RoomChange room_change = 1;
   */
  roomChange?: RoomChange | undefined;
};

/**
 * Describes the message admin.v1.GetRoomChangeResponse.
 * Use `create(GetRoomChangeResponseSchema)` to create a new message.
 */
export declare const GetRoomChangeResponseSchema: GenMessage<GetRoomChangeResponse>;

/**
 * @generated from message admin.v1.CreateRoomChangeRequest
 */
export declare type CreateRoomChangeRequest = Message<"admin.v1.CreateRoomChangeRequest"> & {
  /**
   * @generated from field: string subject_id = 1;
   */
  subjectId: string;

  /**
   * @generated from field: google.type.Date date = 2;
   */
  date?: Date | undefined;

  /**
   * @generated from field: admin.v1.Period period = 3;
   */
  period: Period;

  /**
   * @generated from field: string original_room_id = 4;
   */
  originalRoomId: string;

  /**
   * @generated from field: string new_room_id = 5;
   */
  newRoomId: string;
};

/**
 * Describes the message admin.v1.CreateRoomChangeRequest.
 * Use `create(CreateRoomChangeRequestSchema)` to create a new message.
 */
export declare const CreateRoomChangeRequestSchema: GenMessage<CreateRoomChangeRequest>;

/**
 * @generated from message admin.v1.CreateRoomChangeResponse
 */
export declare type CreateRoomChangeResponse = Message<"admin.v1.CreateRoomChangeResponse"> & {
  /**
   * @generated from field: admin.v1.RoomChange room_change = 1;
   */
  roomChange?: RoomChange | undefined;
};

/**
 * Describes the message admin.v1.CreateRoomChangeResponse.
 * Use `create(CreateRoomChangeResponseSchema)` to create a new message.
 */
export declare const CreateRoomChangeResponseSchema: GenMessage<CreateRoomChangeResponse>;

/**
 * @generated from message admin.v1.UpdateRoomChangeRequest
 */
export declare type UpdateRoomChangeRequest = Message<"admin.v1.UpdateRoomChangeRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string subject_id = 2;
   */
  subjectId: string;

  /**
   * @generated from field: google.type.Date date = 3;
   */
  date?: Date | undefined;

  /**
   * @generated from field: admin.v1.Period period = 4;
   */
  period: Period;

  /**
   * @generated from field: string original_room_id = 5;
   */
  originalRoomId: string;

  /**
   * @generated from field: string new_room_id = 6;
   */
  newRoomId: string;

  /**
   * @generated from field: google.protobuf.FieldMask update_mask = 99;
   */
  updateMask?: FieldMask | undefined;
};

/**
 * Describes the message admin.v1.UpdateRoomChangeRequest.
 * Use `create(UpdateRoomChangeRequestSchema)` to create a new message.
 */
export declare const UpdateRoomChangeRequestSchema: GenMessage<UpdateRoomChangeRequest>;

/**
 * @generated from message admin.v1.UpdateRoomChangeResponse
 */
export declare type UpdateRoomChangeResponse = Message<"admin.v1.UpdateRoomChangeResponse"> & {
  /**
   * @generated from field: admin.v1.RoomChange room_change = 1;
   */
  roomChange?: RoomChange | undefined;
};

/**
 * Describes the message admin.v1.UpdateRoomChangeResponse.
 * Use `create(UpdateRoomChangeResponseSchema)` to create a new message.
 */
export declare const UpdateRoomChangeResponseSchema: GenMessage<UpdateRoomChangeResponse>;

/**
 * @generated from message admin.v1.DeleteRoomChangeRequest
 */
export declare type DeleteRoomChangeRequest = Message<"admin.v1.DeleteRoomChangeRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message admin.v1.DeleteRoomChangeRequest.
 * Use `create(DeleteRoomChangeRequestSchema)` to create a new message.
 */
export declare const DeleteRoomChangeRequestSchema: GenMessage<DeleteRoomChangeRequest>;

/**
 * @generated from message admin.v1.DeleteRoomChangeResponse
 */
export declare type DeleteRoomChangeResponse = Message<"admin.v1.DeleteRoomChangeResponse"> & {
};

/**
 * Describes the message admin.v1.DeleteRoomChangeResponse.
 * Use `create(DeleteRoomChangeResponseSchema)` to create a new message.
 */
export declare const DeleteRoomChangeResponseSchema: GenMessage<DeleteRoomChangeResponse>;

/**
 * @generated from service admin.v1.RoomChangeService
 */
export declare const RoomChangeService: GenService<{
  /**
   * @generated from rpc admin.v1.RoomChangeService.ListRoomChanges
   */
  listRoomChanges: {
    methodKind: "unary";
    input: typeof ListRoomChangesRequestSchema;
    output: typeof ListRoomChangesResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.RoomChangeService.GetRoomChange
   */
  getRoomChange: {
    methodKind: "unary";
    input: typeof GetRoomChangeRequestSchema;
    output: typeof GetRoomChangeResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.RoomChangeService.CreateRoomChange
   */
  createRoomChange: {
    methodKind: "unary";
    input: typeof CreateRoomChangeRequestSchema;
    output: typeof CreateRoomChangeResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.RoomChangeService.UpdateRoomChange
   */
  updateRoomChange: {
    methodKind: "unary";
    input: typeof UpdateRoomChangeRequestSchema;
    output: typeof UpdateRoomChangeResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.RoomChangeService.DeleteRoomChange
   */
  deleteRoomChange: {
    methodKind: "unary";
    input: typeof DeleteRoomChangeRequestSchema;
    output: typeof DeleteRoomChangeResponseSchema;
  },
}>;

