// @generated by protoc-gen-es v2.16.0
// @generated from file admin/v1/room.proto (package admin.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, serviceDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_field_mask, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file admin/v1/room.proto.
 */
export const file_admin_v1_room = /*@__PURE__*/
  fileDesc("ChNhZG1pbi92MS9yb29tLnByb3RvEghhZG1pbi52MSKkAQoEUm9vbRIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJEiIKBWZsb29yGAMgASgOMhMuYWRtaW4udjEuUm9vbUZsb29yEi4KCmNyZWF0ZWRfYXQYBCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4KCnVwZGF0ZWRfYXQYBSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wIjkKEExpc3RSb29tc1JlcXVlc3QSEQoJcGFnZV9zaXplGAEgASgFEhIKCnBhZ2VfdG9rZW4YAiABKAkiSwoRTGlzdFJvb21zUmVzcG9uc2USHQoFcm9vbXMYASADKAsyDi5hZG1pbi52MS5Sb29tEhcKD25leHRfcGFnZV90b2tlbhgCIAEoCSIcCg5HZXRSb29tUmVxdWVzdBIKCgJpZBgBIAEoCSIvCg9HZXRSb29tUmVzcG9uc2USHAoEcm9vbRgBIAEoCzIOLmFkbWluLnYxLlJvb20iRQoRQ3JlYXRlUm9vbVJlcXVlc3QSDAoEbmFtZRgBIAEoCRIiCgVmbG9vchgCIAEoDjITLmFkbWluLnYxLlJvb21GbG9vciIyChJDcmVhdGVSb29tUmVzcG9uc2USHAoEcm9vbRgBIAEoCzIOLmFkbWluLnYxLlJvb20iggEKEVVwZGF0ZVJvb21SZXF1ZXN0EgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAkSIgoFZmxvb3IYAyABKA4yEy5hZG1pbi52MS5Sb29tRmxvb3ISLwoLdXBkYXRlX21hc2sYYyABKAsyGi5nb29nbGUucHJvdG9idWYuRmllbGRNYXNrIjIKElVwZGF0ZVJvb21SZXNwb25zZRIcCgRyb29tGAEgASgLMg4uYWRtaW4udjEuUm9vbSIfChFEZWxldGVSb29tUmVxdWVzdBIKCgJpZBgBIAEoCSIUChJEZWxldGVSb29tUmVzcG9uc2UqvQEKCVJvb21GbG9vchIaChZST09NX0ZMT09SX1VOU1BFQ0lGSUVEEAASEAoMUk9PTV9GTE9PUl8xEAESEAoMUk9PTV9GTE9PUl8yEAISEAoMUk9PTV9GTE9PUl8zEAMSEAoMUk9PTV9GTE9PUl80EAQSEAoMUk9PTV9GTE9PUl81EAUSEAoMUk9PTV9GTE9PUl82EAYSEAoMUk9PTV9GTE9PUl83EAcSFgoSUk9PTV9GTE9PUl9WSVJUVUFMEAgy7gIKC1Jvb21TZXJ2aWNlEkQKCUxpc3RSb29tcxIaLmFkbWluLnYxLkxpc3RSb29tc1JlcXVlc3QaGy5hZG1pbi52MS5MaXN0Um9vbXNSZXNwb25zZRI+CgdHZXRSb29tEhguYWRtaW4udjEuR2V0Um9vbVJlcXVlc3QaGS5hZG1pbi52MS5HZXRSb29tUmVzcG9uc2USRwoKQ3JlYXRlUm9vbRIbLmFkbWluLnYxLkNyZWF0ZVJvb21SZXF1ZXN0GhwuYWRtaW4udjEuQ3JlYXRlUm9vbVJlc3BvbnNlEkcKClVwZGF0ZVJvb20SGy5hZG1pbi52MS5VcGRhdGVSb29tUmVxdWVzdBocLmFkbWluLnYxLlVwZGF0ZVJvb21SZXNwb25zZRJHCgpEZWxldGVSb29tEhsuYWRtaW4udjEuRGVsZXRlUm9vbVJlcXVlc3QaHC5hZG1pbi52MS5EZWxldGVSb29tUmVzcG9uc2ViBnByb3RvMw", [file_google_protobuf_field_mask, file_google_protobuf_timestamp]);

/**
 * Describes the message admin.v1.Room.
 * Use `create(RoomSchema)` to create a new message.
 */
export const RoomSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_room, 0);

/**
 * Describes the message admin.v1.ListRoomsRequest.
 * Use `create(ListRoomsRequestSchema)` to create a new message.
 */
export const ListRoomsRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_room, 1);

/**
 * Describes the message admin.v1.ListRoomsResponse.
 * Use `create(ListRoomsResponseSchema)` to create a new message.
 */
export const ListRoomsResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_room, 2);

/**
 * Describes the message admin.v1.GetRoomRequest.
 * Use `create(GetRoomRequestSchema)` to create a new message.
 */
export const GetRoomRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_room, 3);

/**
 * Describes the message admin.v1.GetRoomResponse.
 * Use `create(GetRoomResponseSchema)` to create a new message.
 */
export const GetRoomResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_room, 4);

/**
 * Describes the message admin.v1.CreateRoomRequest.
 * Use `create(CreateRoomRequestSchema)` to create a new message.
 */
export const CreateRoomRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_room, 5);

/**
 * Describes the message admin.v1.CreateRoomResponse.
 * Use `create(CreateRoomResponseSchema)` to create a new message.
 */
export const CreateRoomResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_room, 6);

/**
 * Describes the message admin.v1.UpdateRoomRequest.
 * Use `create(UpdateRoomRequestSchema)` to create a new message.
 */
export const UpdateRoomRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_room, 7);

/**
 * Describes the message admin.v1.UpdateRoomResponse.
 * Use `create(UpdateRoomResponseSchema)` to create a new message.
 */
export const UpdateRoomResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_room, 8);

/**
 * Describes the message admin.v1.DeleteRoomRequest.
 * Use `create(DeleteRoomRequestSchema)` to create a new message.
 */
export const DeleteRoomRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_room, 9);

/**
 * Describes the message admin.v1.DeleteRoomResponse.
 * Use `create(DeleteRoomResponseSchema)` to create a new message.
 */
export const DeleteRoomResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_room, 10);

/**
 * Describes the enum admin.v1.RoomFloor.
 */
export const RoomFloorSchema = /*@__PURE__*/
  enumDesc(file_admin_v1_room, 0);

/**
 * @generated from enum admin.v1.RoomFloor
 */
export const RoomFloor = /*@__PURE__*/
  tsEnum(RoomFloorSchema);

/**
 * @generated from service admin.v1.RoomService
 */
export const RoomService = /*@__PURE__*/
  serviceDesc(file_admin_v1_room, 0);

