// @generated by protoc-gen-es v2.16.0
// @generated from file admin/v1/route.proto (package admin.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_field_mask } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file admin/v1/route.proto.
 */
export const file_admin_v1_route = /*@__PURE__*/
  fileDesc("ChRhZG1pbi92MS9yb3V0ZS5wcm90bxIIYWRtaW4udjEiMwoFUm91dGUSEAoIcm91dGVfaWQYASABKAkSGAoQcm91dGVfc2hvcnRfbmFtZRgCIAEoCSI6ChFMaXN0Um91dGVzUmVxdWVzdBIRCglwYWdlX3NpemUYASABKAUSEgoKcGFnZV90b2tlbhgCIAEoCSJOChJMaXN0Um91dGVzUmVzcG9uc2USHwoGcm91dGVzGAEgAygLMg8uYWRtaW4udjEuUm91dGUSFwoPbmV4dF9wYWdlX3Rva2VuGAIgASgJIiMKD0dldFJvdXRlUmVxdWVzdBIQCghyb3V0ZV9pZBgBIAEoCSIyChBHZXRSb3V0ZVJlc3BvbnNlEh4KBXJvdXRlGAEgASgLMg8uYWRtaW4udjEuUm91dGUiQAoSQ3JlYXRlUm91dGVSZXF1ZXN0EhAKCHJvdXRlX2lkGAEgASgJEhgKEHJvdXRlX3Nob3J0X25hbWUYAiABKAkiNQoTQ3JlYXRlUm91dGVSZXNwb25zZRIeCgVyb3V0ZRgBIAEoCzIPLmFkbWluLnYxLlJvdXRlInEKElVwZGF0ZVJvdXRlUmVxdWVzdBIQCghyb3V0ZV9pZBgBIAEoCRIYChByb3V0ZV9zaG9ydF9uYW1lGAIgASgJEi8KC3VwZGF0ZV9tYXNrGGMgASgLMhouZ29vZ2xlLnByb3RvYnVmLkZpZWxkTWFzayI1ChNVcGRhdGVSb3V0ZVJlc3BvbnNlEh4KBXJvdXRlGAEgASgLMg8uYWRtaW4udjEuUm91dGUiJgoSRGVsZXRlUm91dGVSZXF1ZXN0EhAKCHJvdXRlX2lkGAEgASgJIhUKE0RlbGV0ZVJvdXRlUmVzcG9uc2Uy/gIKDFJvdXRlU2VydmljZRJHCgpMaXN0Um91dGVzEhsuYWRtaW4udjEuTGlzdFJvdXRlc1JlcXVlc3QaHC5hZG1pbi52MS5MaXN0Um91dGVzUmVzcG9uc2USQQoIR2V0Um91dGUSGS5hZG1pbi52MS5HZXRSb3V0ZVJlcXVlc3QaGi5hZG1pbi52MS5HZXRSb3V0ZVJlc3BvbnNlEkoKC0NyZWF0ZVJvdXRlEhwuYWRtaW4udjEuQ3JlYXRlUm91dGVSZXF1ZXN0Gh0uYWRtaW4udjEuQ3JlYXRlUm91dGVSZXNwb25zZRJKCgtVcGRhdGVSb3V0ZRIcLmFkbWluLnYxLlVwZGF0ZVJvdXRlUmVxdWVzdBodLmFkbWluLnYxLlVwZGF0ZVJvdXRlUmVzcG9uc2USSgoLRGVsZXRlUm91dGUSHC5hZG1pbi52MS5EZWxldGVSb3V0ZVJlcXVlc3QaHS5hZG1pbi52MS5EZWxldGVSb3V0ZVJlc3BvbnNlYgZwcm90bzM", [file_google_protobuf_field_mask]);

/**
 * Describes the message admin.v1.Route.
 * Use `create(RouteSchema)` to create a new message.
 */
export const RouteSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_route, 0);

/**
 * Describes the message admin.v1.ListRoutesRequest.
 * Use `create(ListRoutesRequestSchema)` to create a new message.
 */
export const ListRoutesRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_route, 1);

/**
 * Describes the message admin.v1.ListRoutesResponse.
 * Use `create(ListRoutesResponseSchema)` to create a new message.
 */
export const ListRoutesResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_route, 2);

/**
 * Describes the message admin.v1.GetRouteRequest.
 * Use `create(GetRouteRequestSchema)` to create a new message.
 */
export const GetRouteRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_route, 3);

/**
 * Describes the message admin.v1.GetRouteResponse.
 * Use `create(GetRouteResponseSchema)` to create a new message.
 */
export const GetRouteResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_route, 4);

/**
 * Describes the message admin.v1.CreateRouteRequest.
 * Use `create(CreateRouteRequestSchema)` to create a new message.
 */
export const CreateRouteRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_route, 5);

/**
 * Describes the message admin.v1.CreateRouteResponse.
 * Use `create(CreateRouteResponseSchema)` to create a new message.
 */
export const CreateRouteResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_route, 6);

/**
 * Describes the message admin.v1.UpdateRouteRequest.
 * Use `create(UpdateRouteRequestSchema)` to create a new message.
 */
export const UpdateRouteRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_route, 7);

/**
 * Describes the message admin.v1.UpdateRouteResponse.
 * Use `create(UpdateRouteResponseSchema)` to create a new message.
 */
export const UpdateRouteResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_route, 8);

/**
 * Describes the message admin.v1.DeleteRouteRequest.
 * Use `create(DeleteRouteRequestSchema)` to create a new message.
 */
export const DeleteRouteRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_route, 9);

/**
 * Describes the message admin.v1.DeleteRouteResponse.
 * Use `create(DeleteRouteResponseSchema)` to create a new message.
 */
export const DeleteRouteResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_route, 10);

/**
 * @generated from service admin.v1.RouteService
 */
export const RouteService = /*@__PURE__*/
  serviceDesc(file_admin_v1_route, 0);

