// @generated by protoc-gen-es v2.16.0
// @generated from file admin/v1/stop.proto (package admin.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { LatLng } from "../../google/type/latlng_pb";
import type { FieldMask } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file admin/v1/stop.proto.
 */
export declare const file_admin_v1_stop: GenFile;

/**
 * @generated from message admin.v1.Stop
 */
export declare type Stop = Message<"admin.v1.Stop"> & {
  /**
   * @generated from field: string stop_id = 1;
   */
  stopId: string;

  /**
   * @generated from field: string stop_name = 2;
   */
  stopName: string;

  /**
   * @generated from field: google.type.LatLng stop_location = 3;
   */
  stopLocation?: LatLng | undefined;

  /**
   * @generated from field: optional string zone_id = 4;
   */
  zoneId?: string | undefined;
};

/**
 * Describes the message admin.v1.Stop.
 * Use `create(StopSchema)` to create a new message.
 */
export declare const StopSchema: GenMessage<Stop>;

/**
 * @generated from message admin.v1.ListStopsRequest
 */
export declare type ListStopsRequest = Message<"admin.v1.ListStopsRequest"> & {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;
};

/**
 * Describes the message admin.v1.ListStopsRequest.
 * Use `create(ListStopsRequestSchema)` to create a new message.
 */
export declare const ListStopsRequestSchema: GenMessage<ListStopsRequest>;

/**
 * @generated from message admin.v1.ListStopsResponse
 */
export declare type ListStopsResponse = Message<"admin.v1.ListStopsResponse"> & {
  /**
   * @generated from field: repeated admin.v1.Stop stops = 1;
   */
  stops: Stop[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message admin.v1.ListStopsResponse.
 * Use `create(ListStopsResponseSchema)` to create a new message.
 */
export declare const ListStopsResponseSchema: GenMessage<ListStopsResponse>;

/**
 * @generated from message admin.v1.GetStopRequest
 */
export declare type GetStopRequest = Message<"admin.v1.GetStopRequest"> & {
  /**
   * @generated from field: string stop_id = 1;
   */
  stopId: string;
};

/**
 * Describes the message admin.v1.GetStopRequest.
 * Use `create(GetStopRequestSchema)` to create a new message.
 */
export declare const GetStopRequestSchema: GenMessage<GetStopRequest>;

/**
 * @generated from message admin.v1.GetStopResponse
 */
export declare type GetStopResponse = Message<"admin.v1.GetStopResponse"> & {
  /**
   * @generated from field: admin.v1.Stop stop = 1;
   */
  stop?: Stop | undefined;
};

/**
 * Describes the message admin.v1.GetStopResponse.
 * Use `create(GetStopResponseSchema)` to create a new message.
 */
export declare const GetStopResponseSchema: GenMessage<GetStopResponse>;

/**
 * @generated from message admin.v1.CreateStopRequest
 */
export declare type CreateStopRequest = Message<"admin.v1.CreateStopRequest"> & {
  /**
   * @generated from field: string stop_id = 1;
   */
  stopId: string;

  /**
   * @generated from field: string stop_name = 2;
   */
  stopName: string;

  /**
   * @generated from field: google.type.LatLng stop_location = 3;
   */
  stopLocation?: LatLng | undefined;

  /**
   * @generated from field: optional string zone_id = 4;
   */
  zoneId?: string | undefined;
};

/**
 * Describes the message admin.v1.CreateStopRequest.
 * Use `create(CreateStopRequestSchema)` to create a new message.
 */
export declare const CreateStopRequestSchema: GenMessage<CreateStopRequest>;

/**
 * @generated from message admin.v1.CreateStopResponse
 */
export declare type CreateStopResponse = Message<"admin.v1.CreateStopResponse"> & {
  /**
   * @generated from field: admin.v1.Stop stop = 1;
   */
  stop?: Stop | undefined;
};

/**
 * Describes the message admin.v1.CreateStopResponse.
 * Use `create(CreateStopResponseSchema)` to create a new message.
 */
export declare const CreateStopResponseSchema: GenMessage<CreateStopResponse>;

/**
 * @generated from message admin.v1.UpdateStopRequest
 */
export declare type UpdateStopRequest = Message<"admin.v1.UpdateStopRequest"> & {
  /**
   * @generated from field: string stop_id = 1;
   */
  stopId: string;

  /**
   * @generated from field: string stop_name = 2;
   */
  stopName: string;

  /**
   * @generated from field: google.type.LatLng stop_location = 3;
   */
  stopLocation?: LatLng | undefined;

  /**
   * @generated from field: optional string zone_id = 4;
   */
  zoneId?: string | undefined;

  /**
   * @generated from field: google.protobuf.FieldMask update_mask = 99;
   */
  updateMask?: FieldMask | undefined;
};

/**
 * Describes the message admin.v1.UpdateStopRequest.
 * Use `create(UpdateStopRequestSchema)` to create a new message.
 */
export declare const UpdateStopRequestSchema: GenMessage<UpdateStopRequest>;

/**
 * @generated from message admin.v1.UpdateStopResponse
 */
export declare type UpdateStopResponse = Message<"admin.v1.UpdateStopResponse"> & {
  /**
   * @generated from field: admin.v1.Stop stop = 1;
   */
  stop?: Stop | undefined;
};

/**
 * Describes the message admin.v1.UpdateStopResponse.
 * Use `create(UpdateStopResponseSchema)` to create a new message.
 */
export declare const UpdateStopResponseSchema: GenMessage<UpdateStopResponse>;

/**
 * @generated from message admin.v1.DeleteStopRequest
 */
export declare type DeleteStopRequest = Message<"admin.v1.DeleteStopRequest"> & {
  /**
   * @generated from field: string stop_id = 1;
   */
  stopId: string;
};

/**
 * Describes the message admin.v1.DeleteStopRequest.
 * Use `create(DeleteStopRequestSchema)` to create a new message.
 */
export declare const DeleteStopRequestSchema: GenMessage<DeleteStopRequest>;

/**
 * @generated from message admin.v1.DeleteStopResponse
 */
export declare type DeleteStopResponse = Message<"admin.v1.DeleteStopResponse"> & {
};

/**
 * Describes the message admin.v1.DeleteStopResponse.
 * Use `create(DeleteStopResponseSchema)` to create a new message.
 */
export declare const DeleteStopResponseSchema: GenMessage<DeleteStopResponse>;

/**
 * @generated from service admin.v1.StopService
 */
export declare const StopService: GenService<{
  /**
   * @generated from rpc admin.v1.StopService.ListStops
   */
  listStops: {
    methodKind: "unary";
    input: typeof ListStopsRequestSchema;
    output: typeof ListStopsResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.StopService.GetStop
   */
  getStop: {
    methodKind: "unary";
    input: typeof GetStopRequestSchema;
    output: typeof GetStopResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.StopService.CreateStop
   */
  createStop: {
    methodKind: "unary";
    input: typeof CreateStopRequestSchema;
    output: typeof CreateStopResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.StopService.UpdateStop
   */
  updateStop: {
    methodKind: "unary";
    input: typeof UpdateStopRequestSchema;
    output: typeof UpdateStopResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.StopService.DeleteStop
   */
  deleteStop: {
    methodKind: "unary";
    input: typeof DeleteStopRequestSchema;
    output: typeof DeleteStopResponseSchema;
  },
}>;

