// @generated by protoc-gen-es v2.16.0
// @generated from file admin/v1/stop.proto (package admin.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_field_mask } from "@bufbuild/protobuf/wkt";
import { file_google_type_latlng } from "../../google/type/latlng_pb";

/**
 * Describes the file admin/v1/stop.proto.
 */
export const file_admin_v1_stop = /*@__PURE__*/
  fileDesc("ChNhZG1pbi92MS9zdG9wLnByb3RvEghhZG1pbi52MSJ4CgRTdG9wEg8KB3N0b3BfaWQYASABKAkSEQoJc3RvcF9uYW1lGAIgASgJEioKDXN0b3BfbG9jYXRpb24YAyABKAsyEy5nb29nbGUudHlwZS5MYXRMbmcSFAoHem9uZV9pZBgEIAEoCUgAiAEBQgoKCF96b25lX2lkIjkKEExpc3RTdG9wc1JlcXVlc3QSEQoJcGFnZV9zaXplGAEgASgFEhIKCnBhZ2VfdG9rZW4YAiABKAkiSwoRTGlzdFN0b3BzUmVzcG9uc2USHQoFc3RvcHMYASADKAsyDi5hZG1pbi52MS5TdG9wEhcKD25leHRfcGFnZV90b2tlbhgCIAEoCSIhCg5HZXRTdG9wUmVxdWVzdBIPCgdzdG9wX2lkGAEgASgJIi8KD0dldFN0b3BSZXNwb25zZRIcCgRzdG9wGAEgASgLMg4uYWRtaW4udjEuU3RvcCKFAQoRQ3JlYXRlU3RvcFJlcXVlc3QSDwoHc3RvcF9pZBgBIAEoCRIRCglzdG9wX25hbWUYAiABKAkSKgoNc3RvcF9sb2NhdGlvbhgDIAEoCzITLmdvb2dsZS50eXBlLkxhdExuZxIUCgd6b25lX2lkGAQgASgJSACIAQFCCgoIX3pvbmVfaWQiMgoSQ3JlYXRlU3RvcFJlc3BvbnNlEhwKBHN0b3AYASABKAsyDi5hZG1pbi52MS5TdG9wIrYBChFVcGRhdGVTdG9wUmVxdWVzdBIPCgdzdG9wX2lkGAEgASgJEhEKCXN0b3BfbmFtZRgCIAEoCRIqCg1zdG9wX2xvY2F0aW9uGAMgASgLMhMuZ29vZ2xlLnR5cGUuTGF0TG5nEhQKB3pvbmVfaWQYBCABKAlIAIgBARIvCgt1cGRhdGVfbWFzaxhjIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5GaWVsZE1hc2tCCgoIX3pvbmVfaWQiMgoSVXBkYXRlU3RvcFJlc3BvbnNlEhwKBHN0b3AYASABKAsyDi5hZG1pbi52MS5TdG9wIiQKEURlbGV0ZVN0b3BSZXF1ZXN0Eg8KB3N0b3BfaWQYASABKAkiFAoSRGVsZXRlU3RvcFJlc3BvbnNlMu4CCgtTdG9wU2VydmljZRJECglMaXN0U3RvcHMSGi5hZG1pbi52MS5MaXN0U3RvcHNSZXF1ZXN0GhsuYWRtaW4udjEuTGlzdFN0b3BzUmVzcG9uc2USPgoHR2V0U3RvcBIYLmFkbWluLnYxLkdldFN0b3BSZXF1ZXN0GhkuYWRtaW4udjEuR2V0U3RvcFJlc3BvbnNlEkcKCkNyZWF0ZVN0b3ASGy5hZG1pbi52MS5DcmVhdGVTdG9wUmVxdWVzdBocLmFkbWluLnYxLkNyZWF0ZVN0b3BSZXNwb25zZRJHCgpVcGRhdGVTdG9wEhsuYWRtaW4udjEuVXBkYXRlU3RvcFJlcXVlc3QaHC5hZG1pbi52MS5VcGRhdGVTdG9wUmVzcG9uc2USRwoKRGVsZXRlU3RvcBIbLmFkbWluLnYxLkRlbGV0ZVN0b3BSZXF1ZXN0GhwuYWRtaW4udjEuRGVsZXRlU3RvcFJlc3BvbnNlYgZwcm90bzM", [file_google_protobuf_field_mask, file_google_type_latlng]);

/**
 * Describes the message admin.v1.Stop.
 * Use `create(StopSchema)` to create a new message.
 */
export const StopSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_stop, 0);

/**
 * Describes the message admin.v1.ListStopsRequest.
 * Use `create(ListStopsRequestSchema)` to create a new message.
 */
export const ListStopsRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_stop, 1);

/**
 * Describes the message admin.v1.ListStopsResponse.
 * Use `create(ListStopsResponseSchema)` to create a new message.
 */
export const ListStopsResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_stop, 2);

/**
 * Describes the message admin.v1.GetStopRequest.
 * Use `create(GetStopRequestSchema)` to create a new message.
 */
export const GetStopRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_stop, 3);

/**
 * Describes the message admin.v1.GetStopResponse.
 * Use `create(GetStopResponseSchema)` to create a new message.
 */
export const GetStopResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_stop, 4);

/**
 * Describes the message admin.v1.CreateStopRequest.
 * Use `create(CreateStopRequestSchema)` to create a new message.
 */
export const CreateStopRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_stop, 5);

/**
 * Describes the message admin.v1.CreateStopResponse.
 * Use `create(CreateStopResponseSchema)` to create a new message.
 */
export const CreateStopResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_stop, 6);

/**
 * Describes the message admin.v1.UpdateStopRequest.
 * Use `create(UpdateStopRequestSchema)` to create a new message.
 */
export const UpdateStopRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_stop, 7);

/**
 * Describes the message admin.v1.UpdateStopResponse.
 * Use `create(UpdateStopResponseSchema)` to create a new message.
 */
export const UpdateStopResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_stop, 8);

/**
 * Describes the message admin.v1.DeleteStopRequest.
 * Use `create(DeleteStopRequestSchema)` to create a new message.
 */
export const DeleteStopRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_stop, 9);

/**
 * Describes the message admin.v1.DeleteStopResponse.
 * Use `create(DeleteStopResponseSchema)` to create a new message.
 */
export const DeleteStopResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_stop, 10);

/**
 * @generated from service admin.v1.StopService
 */
export const StopService = /*@__PURE__*/
  serviceDesc(file_admin_v1_stop, 0);

