// @generated by protoc-gen-es v2.16.0
// @generated from file admin/v1/syllabus.proto (package admin.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { FieldMask, Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file admin/v1/syllabus.proto.
 */
export declare const file_admin_v1_syllabus: GenFile;

/**
 * @generated from message admin.v1.Syllabus
 */
export declare type Syllabus = Message<"admin.v1.Syllabus"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string en_name = 3;
   */
  enName: string;

  /**
   * @generated from field: string grades = 4;
   */
  grades: string;

  /**
   * @generated from field: int32 credit = 5;
   */
  credit: number;

  /**
   * @generated from field: string faculty_names = 6;
   */
  facultyNames: string;

  /**
   * @generated from field: string practical_home_faculty_category = 7;
   */
  practicalHomeFacultyCategory: string;

  /**
   * @generated from field: string multiple_person_teaching_form = 8;
   */
  multiplePersonTeachingForm: string;

  /**
   * @generated from field: string teaching_form = 9;
   */
  teachingForm: string;

  /**
   * @generated from field: string summary = 10;
   */
  summary: string;

  /**
   * @generated from field: string learning_outcomes = 11;
   */
  learningOutcomes: string;

  /**
   * @generated from field: string assignments = 12;
   */
  assignments: string;

  /**
   * @generated from field: string evaluation_method = 13;
   */
  evaluationMethod: string;

  /**
   * @generated from field: string textbooks = 14;
   */
  textbooks: string;

  /**
   * @generated from field: string reference_books = 15;
   */
  referenceBooks: string;

  /**
   * @generated from field: string prerequisites = 16;
   */
  prerequisites: string;

  /**
   * @generated from field: string pre_learning = 17;
   */
  preLearning: string;

  /**
   * @generated from field: string post_learning = 18;
   */
  postLearning: string;

  /**
   * @generated from field: string notes = 19;
   */
  notes: string;

  /**
   * @generated from field: string keywords = 20;
   */
  keywords: string;

  /**
   * @generated from field: string target_courses = 21;
   */
  targetCourses: string;

  /**
   * @generated from field: string target_areas = 22;
   */
  targetAreas: string;

  /**
   * @generated from field: string classifications = 23;
   */
  classifications: string;

  /**
   * @generated from field: string teaching_language = 24;
   */
  teachingLanguage: string;

  /**
   * @generated from field: string contents_and_schedule = 25;
   */
  contentsAndSchedule: string;

  /**
   * @generated from field: string teaching_and_exam_form = 26;
   */
  teachingAndExamForm: string;

  /**
   * @generated from field: string dsop_subject = 27;
   */
  dsopSubject: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 28;
   */
  createdAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 29;
   */
  updatedAt?: Timestamp | undefined;
};

/**
 * Describes the message admin.v1.Syllabus.
 * Use `create(SyllabusSchema)` to create a new message.
 */
export declare const SyllabusSchema: GenMessage<Syllabus>;

/**
 * @generated from message admin.v1.ListSyllabiRequest
 */
export declare type ListSyllabiRequest = Message<"admin.v1.ListSyllabiRequest"> & {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;
};

/**
 * Describes the message admin.v1.ListSyllabiRequest.
 * Use `create(ListSyllabiRequestSchema)` to create a new message.
 */
export declare const ListSyllabiRequestSchema: GenMessage<ListSyllabiRequest>;

/**
 * @generated from message admin.v1.ListSyllabiResponse
 */
export declare type ListSyllabiResponse = Message<"admin.v1.ListSyllabiResponse"> & {
  /**
   * @generated from field: repeated admin.v1.Syllabus syllabi = 1;
   */
  syllabi: Syllabus[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message admin.v1.ListSyllabiResponse.
 * Use `create(ListSyllabiResponseSchema)` to create a new message.
 */
export declare const ListSyllabiResponseSchema: GenMessage<ListSyllabiResponse>;

/**
 * @generated from message admin.v1.GetSyllabusRequest
 */
export declare type GetSyllabusRequest = Message<"admin.v1.GetSyllabusRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message admin.v1.GetSyllabusRequest.
 * Use `create(GetSyllabusRequestSchema)` to create a new message.
 */
export declare const GetSyllabusRequestSchema: GenMessage<GetSyllabusRequest>;

/**
 * @generated from message admin.v1.GetSyllabusResponse
 */
export declare type GetSyllabusResponse = Message<"admin.v1.GetSyllabusResponse"> & {
  /**
   * @generated from field: admin.v1.Syllabus syllabus = 1;
   */
  syllabus?: Syllabus | undefined;
};

/**
 * Describes the message admin.v1.GetSyllabusResponse.
 * Use `create(GetSyllabusResponseSchema)` to create a new message.
 */
export declare const GetSyllabusResponseSchema: GenMessage<GetSyllabusResponse>;

/**
 * @generated from message admin.v1.CreateSyllabusRequest
 */
export declare type CreateSyllabusRequest = Message<"admin.v1.CreateSyllabusRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string en_name = 3;
   */
  enName: string;

  /**
   * @generated from field: string grades = 4;
   */
  grades: string;

  /**
   * @generated from field: int32 credit = 5;
   */
  credit: number;

  /**
   * @generated from field: string faculty_names = 6;
   */
  facultyNames: string;

  /**
   * @generated from field: string practical_home_faculty_category = 7;
   */
  practicalHomeFacultyCategory: string;

  /**
   * @generated from field: string multiple_person_teaching_form = 8;
   */
  multiplePersonTeachingForm: string;

  /**
   * @generated from field: string teaching_form = 9;
   */
  teachingForm: string;

  /**
   * @generated from field: string summary = 10;
   */
  summary: string;

  /**
   * @generated from field: string learning_outcomes = 11;
   */
  learningOutcomes: string;

  /**
   * @generated from field: string assignments = 12;
   */
  assignments: string;

  /**
   * @generated from field: string evaluation_method = 13;
   */
  evaluationMethod: string;

  /**
   * @generated from field: string textbooks = 14;
   */
  textbooks: string;

  /**
   * @generated from field: string reference_books = 15;
   */
  referenceBooks: string;

  /**
   * @generated from field: string prerequisites = 16;
   */
  prerequisites: string;

  /**
   * @generated from field: string pre_learning = 17;
   */
  preLearning: string;

  /**
   * @generated from field: string post_learning = 18;
   */
  postLearning: string;

  /**
   * @generated from field: string notes = 19;
   */
  notes: string;

  /**
   * @generated from field: string keywords = 20;
   */
  keywords: string;

  /**
   * @generated from field: string target_courses = 21;
   */
  targetCourses: string;

  /**
   * @generated from field: string target_areas = 22;
   */
  targetAreas: string;

  /**
   * @generated from field: string classifications = 23;
   */
  classifications: string;

  /**
   * @generated from field: string teaching_language = 24;
   */
  teachingLanguage: string;

  /**
   * @generated from field: string contents_and_schedule = 25;
   */
  contentsAndSchedule: string;

  /**
   * @generated from field: string teaching_and_exam_form = 26;
   */
  teachingAndExamForm: string;

  /**
   * @generated from field: string dsop_subject = 27;
   */
  dsopSubject: string;
};

/**
 * Describes the message admin.v1.CreateSyllabusRequest.
 * Use `create(CreateSyllabusRequestSchema)` to create a new message.
 */
export declare const CreateSyllabusRequestSchema: GenMessage<CreateSyllabusRequest>;

/**
 * @generated from message admin.v1.CreateSyllabusResponse
 */
export declare type CreateSyllabusResponse = Message<"admin.v1.CreateSyllabusResponse"> & {
  /**
   * @generated from field: admin.v1.Syllabus syllabus = 1;
   */
  syllabus?: Syllabus | undefined;
};

/**
 * Describes the message admin.v1.CreateSyllabusResponse.
 * Use `create(CreateSyllabusResponseSchema)` to create a new message.
 */
export declare const CreateSyllabusResponseSchema: GenMessage<CreateSyllabusResponse>;

/**
 * @generated from message admin.v1.UpdateSyllabusRequest
 */
export declare type UpdateSyllabusRequest = Message<"admin.v1.UpdateSyllabusRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string en_name = 3;
   */
  enName: string;

  /**
   * @generated from field: string grades = 4;
   */
  grades: string;

  /**
   * @generated from field: int32 credit = 5;
   */
  credit: number;

  /**
   * @generated from field: string faculty_names = 6;
   */
  facultyNames: string;

  /**
   * @generated from field: string practical_home_faculty_category = 7;
   */
  practicalHomeFacultyCategory: string;

  /**
   * @generated from field: string multiple_person_teaching_form = 8;
   */
  multiplePersonTeachingForm: string;

  /**
   * @generated from field: string teaching_form = 9;
   */
  teachingForm: string;

  /**
   * @generated from field: string summary = 10;
   */
  summary: string;

  /**
   * @generated from field: string learning_outcomes = 11;
   */
  learningOutcomes: string;

  /**
   * @generated from field: string assignments = 12;
   */
  assignments: string;

  /**
   * @generated from field: string evaluation_method = 13;
   */
  evaluationMethod: string;

  /**
   * @generated from field: string textbooks = 14;
   */
  textbooks: string;

  /**
   * @generated from field: string reference_books = 15;
   */
  referenceBooks: string;

  /**
   * @generated from field: string prerequisites = 16;
   */
  prerequisites: string;

  /**
   * @generated from field: string pre_learning = 17;
   */
  preLearning: string;

  /**
   * @generated from field: string post_learning = 18;
   */
  postLearning: string;

  /**
   * @generated from field: string notes = 19;
   */
  notes: string;

  /**
   * @generated from field: string keywords = 20;
   */
  keywords: string;

  /**
   * @generated from field: string target_courses = 21;
   */
  targetCourses: string;

  /**
   * @generated from field: string target_areas = 22;
   */
  targetAreas: string;

  /**
   * @generated from field: string classifications = 23;
   */
  classifications: string;

  /**
   * @generated from field: string teaching_language = 24;
   */
  teachingLanguage: string;

  /**
   * @generated from field: string contents_and_schedule = 25;
   */
  contentsAndSchedule: string;

  /**
   * @generated from field: string teaching_and_exam_form = 26;
   */
  teachingAndExamForm: string;

  /**
   * @generated from field: string dsop_subject = 27;
   */
  dsopSubject: string;

  /**
   * @generated from field: google.protobuf.FieldMask update_mask = 99;
   */
  updateMask?: FieldMask | undefined;
};

/**
 * Describes the message admin.v1.UpdateSyllabusRequest.
 * Use `create(UpdateSyllabusRequestSchema)` to create a new message.
 */
export declare const UpdateSyllabusRequestSchema: GenMessage<UpdateSyllabusRequest>;

/**
 * @generated from message admin.v1.UpdateSyllabusResponse
 */
export declare type UpdateSyllabusResponse = Message<"admin.v1.UpdateSyllabusResponse"> & {
  /**
   * @generated from field: admin.v1.Syllabus syllabus = 1;
   */
  syllabus?: Syllabus | undefined;
};

/**
 * Describes the message admin.v1.UpdateSyllabusResponse.
 * Use `create(UpdateSyllabusResponseSchema)` to create a new message.
 */
export declare const UpdateSyllabusResponseSchema: GenMessage<UpdateSyllabusResponse>;

/**
 * @generated from message admin.v1.DeleteSyllabusRequest
 */
export declare type DeleteSyllabusRequest = Message<"admin.v1.DeleteSyllabusRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message admin.v1.DeleteSyllabusRequest.
 * Use `create(DeleteSyllabusRequestSchema)` to create a new message.
 */
export declare const DeleteSyllabusRequestSchema: GenMessage<DeleteSyllabusRequest>;

/**
 * @generated from message admin.v1.DeleteSyllabusResponse
 */
export declare type DeleteSyllabusResponse = Message<"admin.v1.DeleteSyllabusResponse"> & {
};

/**
 * Describes the message admin.v1.DeleteSyllabusResponse.
 * Use `create(DeleteSyllabusResponseSchema)` to create a new message.
 */
export declare const DeleteSyllabusResponseSchema: GenMessage<DeleteSyllabusResponse>;

/**
 * @generated from service admin.v1.SyllabusService
 */
export declare const SyllabusService: GenService<{
  /**
   * @generated from rpc admin.v1.SyllabusService.ListSyllabi
   */
  listSyllabi: {
    methodKind: "unary";
    input: typeof ListSyllabiRequestSchema;
    output: typeof ListSyllabiResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.SyllabusService.GetSyllabus
   */
  getSyllabus: {
    methodKind: "unary";
    input: typeof GetSyllabusRequestSchema;
    output: typeof GetSyllabusResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.SyllabusService.CreateSyllabus
   */
  createSyllabus: {
    methodKind: "unary";
    input: typeof CreateSyllabusRequestSchema;
    output: typeof CreateSyllabusResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.SyllabusService.UpdateSyllabus
   */
  updateSyllabus: {
    methodKind: "unary";
    input: typeof UpdateSyllabusRequestSchema;
    output: typeof UpdateSyllabusResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.SyllabusService.DeleteSyllabus
   */
  deleteSyllabus: {
    methodKind: "unary";
    input: typeof DeleteSyllabusRequestSchema;
    output: typeof DeleteSyllabusResponseSchema;
  },
}>;

