// @generated by protoc-gen-es v2.16.0
// @generated from file admin/v1/timetable_item.proto (package admin.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { DayOfWeek } from "../../google/type/dayofweek_pb";
import type { Period } from "./common_pb";
import type { FieldMask, Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file admin/v1/timetable_item.proto.
 */
export declare const file_admin_v1_timetable_item: GenFile;

/**
 * @generated from message admin.v1.TimetableItem
 */
export declare type TimetableItem = Message<"admin.v1.TimetableItem"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string subject_id = 2;
   */
  subjectId: string;

  /**
   * @generated from field: optional google.type.DayOfWeek day_of_week = 3;
   */
  dayOfWeek?: DayOfWeek | undefined;

  /**
   * @generated from field: optional admin.v1.Period period = 4;
   */
  period?: Period | undefined;

  /**
   * @generated from field: repeated string room_ids = 5;
   */
  roomIds: string[];

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 6;
   */
  createdAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 7;
   */
  updatedAt?: Timestamp | undefined;
};

/**
 * Describes the message admin.v1.TimetableItem.
 * Use `create(TimetableItemSchema)` to create a new message.
 */
export declare const TimetableItemSchema: GenMessage<TimetableItem>;

/**
 * @generated from message admin.v1.ListTimetableItemsRequest
 */
export declare type ListTimetableItemsRequest = Message<"admin.v1.ListTimetableItemsRequest"> & {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;
};

/**
 * Describes the message admin.v1.ListTimetableItemsRequest.
 * Use `create(ListTimetableItemsRequestSchema)` to create a new message.
 */
export declare const ListTimetableItemsRequestSchema: GenMessage<ListTimetableItemsRequest>;

/**
 * @generated from message admin.v1.ListTimetableItemsResponse
 */
export declare type ListTimetableItemsResponse = Message<"admin.v1.ListTimetableItemsResponse"> & {
  /**
   * @generated from field: repeated admin.v1.TimetableItem timetable_items = 1;
   */
  timetableItems: TimetableItem[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message admin.v1.ListTimetableItemsResponse.
 * Use `create(ListTimetableItemsResponseSchema)` to create a new message.
 */
export declare const ListTimetableItemsResponseSchema: GenMessage<ListTimetableItemsResponse>;

/**
 * @generated from message admin.v1.GetTimetableItemRequest
 */
export declare type GetTimetableItemRequest = Message<"admin.v1.GetTimetableItemRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message admin.v1.GetTimetableItemRequest.
 * Use `create(GetTimetableItemRequestSchema)` to create a new message.
 */
export declare const GetTimetableItemRequestSchema: GenMessage<GetTimetableItemRequest>;

/**
 * @generated from message admin.v1.GetTimetableItemResponse
 */
export declare type GetTimetableItemResponse = Message<"admin.v1.GetTimetableItemResponse"> & {
  /**
   * @generated from field: admin.v1.TimetableItem timetable_item = 1;
   */
  timetableItem?: TimetableItem | undefined;
};

/**
 * Describes the message admin.v1.GetTimetableItemResponse.
 * Use `create(GetTimetableItemResponseSchema)` to create a new message.
 */
export declare const GetTimetableItemResponseSchema: GenMessage<GetTimetableItemResponse>;

/**
 * @generated from message admin.v1.CreateTimetableItemRequest
 */
export declare type CreateTimetableItemRequest = Message<"admin.v1.CreateTimetableItemRequest"> & {
  /**
   * @generated from field: string subject_id = 1;
   */
  subjectId: string;

  /**
   * @generated from field: optional google.type.DayOfWeek day_of_week = 2;
   */
  dayOfWeek?: DayOfWeek | undefined;

  /**
   * @generated from field: optional admin.v1.Period period = 3;
   */
  period?: Period | undefined;

  /**
   * @generated from field: repeated string room_ids = 4;
   */
  roomIds: string[];
};

/**
 * Describes the message admin.v1.CreateTimetableItemRequest.
 * Use `create(CreateTimetableItemRequestSchema)` to create a new message.
 */
export declare const CreateTimetableItemRequestSchema: GenMessage<CreateTimetableItemRequest>;

/**
 * @generated from message admin.v1.CreateTimetableItemResponse
 */
export declare type CreateTimetableItemResponse = Message<"admin.v1.CreateTimetableItemResponse"> & {
  /**
   * @generated from field: admin.v1.TimetableItem timetable_item = 1;
   */
  timetableItem?: TimetableItem | undefined;
};

/**
 * Describes the message admin.v1.CreateTimetableItemResponse.
 * Use `create(CreateTimetableItemResponseSchema)` to create a new message.
 */
export declare const CreateTimetableItemResponseSchema: GenMessage<CreateTimetableItemResponse>;

/**
 * @generated from message admin.v1.UpdateTimetableItemRequest
 */
export declare type UpdateTimetableItemRequest = Message<"admin.v1.UpdateTimetableItemRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string subject_id = 2;
   */
  subjectId: string;

  /**
   * @generated from field: optional google.type.DayOfWeek day_of_week = 3;
   */
  dayOfWeek?: DayOfWeek | undefined;

  /**
   * @generated from field: optional admin.v1.Period period = 4;
   */
  period?: Period | undefined;

  /**
   * @generated from field: repeated string room_ids = 5;
   */
  roomIds: string[];

  /**
   * @generated from field: google.protobuf.FieldMask update_mask = 99;
   */
  updateMask?: FieldMask | undefined;
};

/**
 * Describes the message admin.v1.UpdateTimetableItemRequest.
 * Use `create(UpdateTimetableItemRequestSchema)` to create a new message.
 */
export declare const UpdateTimetableItemRequestSchema: GenMessage<UpdateTimetableItemRequest>;

/**
 * @generated from message admin.v1.UpdateTimetableItemResponse
 */
export declare type UpdateTimetableItemResponse = Message<"admin.v1.UpdateTimetableItemResponse"> & {
  /**
   * @generated from field: admin.v1.TimetableItem timetable_item = 1;
   */
  timetableItem?: TimetableItem | undefined;
};

/**
 * Describes the message admin.v1.UpdateTimetableItemResponse.
 * Use `create(UpdateTimetableItemResponseSchema)` to create a new message.
 */
export declare const UpdateTimetableItemResponseSchema: GenMessage<UpdateTimetableItemResponse>;

/**
 * @generated from message admin.v1.DeleteTimetableItemRequest
 */
export declare type DeleteTimetableItemRequest = Message<"admin.v1.DeleteTimetableItemRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message admin.v1.DeleteTimetableItemRequest.
 * Use `create(DeleteTimetableItemRequestSchema)` to create a new message.
 */
export declare const DeleteTimetableItemRequestSchema: GenMessage<DeleteTimetableItemRequest>;

/**
 * @generated from message admin.v1.DeleteTimetableItemResponse
 */
export declare type DeleteTimetableItemResponse = Message<"admin.v1.DeleteTimetableItemResponse"> & {
};

/**
 * Describes the message admin.v1.DeleteTimetableItemResponse.
 * Use `create(DeleteTimetableItemResponseSchema)` to create a new message.
 */
export declare const DeleteTimetableItemResponseSchema: GenMessage<DeleteTimetableItemResponse>;

/**
 * @generated from service admin.v1.TimetableItemService
 */
export declare const TimetableItemService: GenService<{
  /**
   * @generated from rpc admin.v1.TimetableItemService.ListTimetableItems
   */
  listTimetableItems: {
    methodKind: "unary";
    input: typeof ListTimetableItemsRequestSchema;
    output: typeof ListTimetableItemsResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.TimetableItemService.GetTimetableItem
   */
  getTimetableItem: {
    methodKind: "unary";
    input: typeof GetTimetableItemRequestSchema;
    output: typeof GetTimetableItemResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.TimetableItemService.CreateTimetableItem
   */
  createTimetableItem: {
    methodKind: "unary";
    input: typeof CreateTimetableItemRequestSchema;
    output: typeof CreateTimetableItemResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.TimetableItemService.UpdateTimetableItem
   */
  updateTimetableItem: {
    methodKind: "unary";
    input: typeof UpdateTimetableItemRequestSchema;
    output: typeof UpdateTimetableItemResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.TimetableItemService.DeleteTimetableItem
   */
  deleteTimetableItem: {
    methodKind: "unary";
    input: typeof DeleteTimetableItemRequestSchema;
    output: typeof DeleteTimetableItemResponseSchema;
  },
}>;

