// @generated by protoc-gen-es v2.16.0
// @generated from file admin/v1/trip.proto (package admin.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, serviceDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_field_mask } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file admin/v1/trip.proto.
 */
export const file_admin_v1_trip = /*@__PURE__*/
  fileDesc("ChNhZG1pbi92MS90cmlwLnByb3RvEghhZG1pbi52MSJ8CgRUcmlwEg8KB3RyaXBfaWQYASABKAkSEAoIcm91dGVfaWQYAiABKAkSEgoKc2VydmljZV9pZBgDIAEoCRIvCglkaXJlY3Rpb24YBCABKA4yFy5hZG1pbi52MS5UcmlwRGlyZWN0aW9uSACIAQFCDAoKX2RpcmVjdGlvbiI5ChBMaXN0VHJpcHNSZXF1ZXN0EhEKCXBhZ2Vfc2l6ZRgBIAEoBRISCgpwYWdlX3Rva2VuGAIgASgJIksKEUxpc3RUcmlwc1Jlc3BvbnNlEh0KBXRyaXBzGAEgAygLMg4uYWRtaW4udjEuVHJpcBIXCg9uZXh0X3BhZ2VfdG9rZW4YAiABKAkiIQoOR2V0VHJpcFJlcXVlc3QSDwoHdHJpcF9pZBgBIAEoCSIvCg9HZXRUcmlwUmVzcG9uc2USHAoEdHJpcBgBIAEoCzIOLmFkbWluLnYxLlRyaXAiiQEKEUNyZWF0ZVRyaXBSZXF1ZXN0Eg8KB3RyaXBfaWQYASABKAkSEAoIcm91dGVfaWQYAiABKAkSEgoKc2VydmljZV9pZBgDIAEoCRIvCglkaXJlY3Rpb24YBCABKA4yFy5hZG1pbi52MS5UcmlwRGlyZWN0aW9uSACIAQFCDAoKX2RpcmVjdGlvbiIyChJDcmVhdGVUcmlwUmVzcG9uc2USHAoEdHJpcBgBIAEoCzIOLmFkbWluLnYxLlRyaXAiugEKEVVwZGF0ZVRyaXBSZXF1ZXN0Eg8KB3RyaXBfaWQYASABKAkSEAoIcm91dGVfaWQYAiABKAkSEgoKc2VydmljZV9pZBgDIAEoCRIvCglkaXJlY3Rpb24YBCABKA4yFy5hZG1pbi52MS5UcmlwRGlyZWN0aW9uSACIAQESLwoLdXBkYXRlX21hc2sYYyABKAsyGi5nb29nbGUucHJvdG9idWYuRmllbGRNYXNrQgwKCl9kaXJlY3Rpb24iMgoSVXBkYXRlVHJpcFJlc3BvbnNlEhwKBHRyaXAYASABKAsyDi5hZG1pbi52MS5UcmlwIiQKEURlbGV0ZVRyaXBSZXF1ZXN0Eg8KB3RyaXBfaWQYASABKAkiFAoSRGVsZXRlVHJpcFJlc3BvbnNlKmgKDVRyaXBEaXJlY3Rpb24SHgoaVFJJUF9ESVJFQ1RJT05fVU5TUEVDSUZJRUQQABIbChdUUklQX0RJUkVDVElPTl9PVVRCT1VORBABEhoKFlRSSVBfRElSRUNUSU9OX0lOQk9VTkQQAjLuAgoLVHJpcFNlcnZpY2USRAoJTGlzdFRyaXBzEhouYWRtaW4udjEuTGlzdFRyaXBzUmVxdWVzdBobLmFkbWluLnYxLkxpc3RUcmlwc1Jlc3BvbnNlEj4KB0dldFRyaXASGC5hZG1pbi52MS5HZXRUcmlwUmVxdWVzdBoZLmFkbWluLnYxLkdldFRyaXBSZXNwb25zZRJHCgpDcmVhdGVUcmlwEhsuYWRtaW4udjEuQ3JlYXRlVHJpcFJlcXVlc3QaHC5hZG1pbi52MS5DcmVhdGVUcmlwUmVzcG9uc2USRwoKVXBkYXRlVHJpcBIbLmFkbWluLnYxLlVwZGF0ZVRyaXBSZXF1ZXN0GhwuYWRtaW4udjEuVXBkYXRlVHJpcFJlc3BvbnNlEkcKCkRlbGV0ZVRyaXASGy5hZG1pbi52MS5EZWxldGVUcmlwUmVxdWVzdBocLmFkbWluLnYxLkRlbGV0ZVRyaXBSZXNwb25zZWIGcHJvdG8z", [file_google_protobuf_field_mask]);

/**
 * Describes the message admin.v1.Trip.
 * Use `create(TripSchema)` to create a new message.
 */
export const TripSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_trip, 0);

/**
 * Describes the message admin.v1.ListTripsRequest.
 * Use `create(ListTripsRequestSchema)` to create a new message.
 */
export const ListTripsRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_trip, 1);

/**
 * Describes the message admin.v1.ListTripsResponse.
 * Use `create(ListTripsResponseSchema)` to create a new message.
 */
export const ListTripsResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_trip, 2);

/**
 * Describes the message admin.v1.GetTripRequest.
 * Use `create(GetTripRequestSchema)` to create a new message.
 */
export const GetTripRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_trip, 3);

/**
 * Describes the message admin.v1.GetTripResponse.
 * Use `create(GetTripResponseSchema)` to create a new message.
 */
export const GetTripResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_trip, 4);

/**
 * Describes the message admin.v1.CreateTripRequest.
 * Use `create(CreateTripRequestSchema)` to create a new message.
 */
export const CreateTripRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_trip, 5);

/**
 * Describes the message admin.v1.CreateTripResponse.
 * Use `create(CreateTripResponseSchema)` to create a new message.
 */
export const CreateTripResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_trip, 6);

/**
 * Describes the message admin.v1.UpdateTripRequest.
 * Use `create(UpdateTripRequestSchema)` to create a new message.
 */
export const UpdateTripRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_trip, 7);

/**
 * Describes the message admin.v1.UpdateTripResponse.
 * Use `create(UpdateTripResponseSchema)` to create a new message.
 */
export const UpdateTripResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_trip, 8);

/**
 * Describes the message admin.v1.DeleteTripRequest.
 * Use `create(DeleteTripRequestSchema)` to create a new message.
 */
export const DeleteTripRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_trip, 9);

/**
 * Describes the message admin.v1.DeleteTripResponse.
 * Use `create(DeleteTripResponseSchema)` to create a new message.
 */
export const DeleteTripResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_trip, 10);

/**
 * Describes the enum admin.v1.TripDirection.
 */
export const TripDirectionSchema = /*@__PURE__*/
  enumDesc(file_admin_v1_trip, 0);

/**
 * @generated from enum admin.v1.TripDirection
 */
export const TripDirection = /*@__PURE__*/
  tsEnum(TripDirectionSchema);

/**
 * @generated from service admin.v1.TripService
 */
export const TripService = /*@__PURE__*/
  serviceDesc(file_admin_v1_trip, 0);

