// @generated by protoc-gen-es v2.16.0
// @generated from file admin/v1/trip.proto (package admin.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { FieldMask } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file admin/v1/trip.proto.
 */
export declare const file_admin_v1_trip: GenFile;

/**
 * @generated from message admin.v1.Trip
 */
export declare type Trip = Message<"admin.v1.Trip"> & {
  /**
   * @generated from field: string trip_id = 1;
   */
  tripId: string;

  /**
   * @generated from field: string route_id = 2;
   */
  routeId: string;

  /**
   * @generated from field: string service_id = 3;
   */
  serviceId: string;

  /**
   * @generated from field: optional admin.v1.TripDirection direction = 4;
   */
  direction?: TripDirection | undefined;
};

/**
 * Describes the message admin.v1.Trip.
 * Use `create(TripSchema)` to create a new message.
 */
export declare const TripSchema: GenMessage<Trip>;

/**
 * @generated from message admin.v1.ListTripsRequest
 */
export declare type ListTripsRequest = Message<"admin.v1.ListTripsRequest"> & {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;
};

/**
 * Describes the message admin.v1.ListTripsRequest.
 * Use `create(ListTripsRequestSchema)` to create a new message.
 */
export declare const ListTripsRequestSchema: GenMessage<ListTripsRequest>;

/**
 * @generated from message admin.v1.ListTripsResponse
 */
export declare type ListTripsResponse = Message<"admin.v1.ListTripsResponse"> & {
  /**
   * @generated from field: repeated admin.v1.Trip trips = 1;
   */
  trips: Trip[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message admin.v1.ListTripsResponse.
 * Use `create(ListTripsResponseSchema)` to create a new message.
 */
export declare const ListTripsResponseSchema: GenMessage<ListTripsResponse>;

/**
 * @generated from message admin.v1.GetTripRequest
 */
export declare type GetTripRequest = Message<"admin.v1.GetTripRequest"> & {
  /**
   * @generated from field: string trip_id = 1;
   */
  tripId: string;
};

/**
 * Describes the message admin.v1.GetTripRequest.
 * Use `create(GetTripRequestSchema)` to create a new message.
 */
export declare const GetTripRequestSchema: GenMessage<GetTripRequest>;

/**
 * @generated from message admin.v1.GetTripResponse
 */
export declare type GetTripResponse = Message<"admin.v1.GetTripResponse"> & {
  /**
   * @generated from field: admin.v1.Trip trip = 1;
   */
  trip?: Trip | undefined;
};

/**
 * Describes the message admin.v1.GetTripResponse.
 * Use `create(GetTripResponseSchema)` to create a new message.
 */
export declare const GetTripResponseSchema: GenMessage<GetTripResponse>;

/**
 * @generated from message admin.v1.CreateTripRequest
 */
export declare type CreateTripRequest = Message<"admin.v1.CreateTripRequest"> & {
  /**
   * @generated from field: string trip_id = 1;
   */
  tripId: string;

  /**
   * @generated from field: string route_id = 2;
   */
  routeId: string;

  /**
   * @generated from field: string service_id = 3;
   */
  serviceId: string;

  /**
   * @generated from field: optional admin.v1.TripDirection direction = 4;
   */
  direction?: TripDirection | undefined;
};

/**
 * Describes the message admin.v1.CreateTripRequest.
 * Use `create(CreateTripRequestSchema)` to create a new message.
 */
export declare const CreateTripRequestSchema: GenMessage<CreateTripRequest>;

/**
 * @generated from message admin.v1.CreateTripResponse
 */
export declare type CreateTripResponse = Message<"admin.v1.CreateTripResponse"> & {
  /**
   * @generated from field: admin.v1.Trip trip = 1;
   */
  trip?: Trip | undefined;
};

/**
 * Describes the message admin.v1.CreateTripResponse.
 * Use `create(CreateTripResponseSchema)` to create a new message.
 */
export declare const CreateTripResponseSchema: GenMessage<CreateTripResponse>;

/**
 * @generated from message admin.v1.UpdateTripRequest
 */
export declare type UpdateTripRequest = Message<"admin.v1.UpdateTripRequest"> & {
  /**
   * @generated from field: string trip_id = 1;
   */
  tripId: string;

  /**
   * @generated from field: string route_id = 2;
   */
  routeId: string;

  /**
   * @generated from field: string service_id = 3;
   */
  serviceId: string;

  /**
   * @generated from field: optional admin.v1.TripDirection direction = 4;
   */
  direction?: TripDirection | undefined;

  /**
   * @generated from field: google.protobuf.FieldMask update_mask = 99;
   */
  updateMask?: FieldMask | undefined;
};

/**
 * Describes the message admin.v1.UpdateTripRequest.
 * Use `create(UpdateTripRequestSchema)` to create a new message.
 */
export declare const UpdateTripRequestSchema: GenMessage<UpdateTripRequest>;

/**
 * @generated from message admin.v1.UpdateTripResponse
 */
export declare type UpdateTripResponse = Message<"admin.v1.UpdateTripResponse"> & {
  /**
   * @generated from field: admin.v1.Trip trip = 1;
   */
  trip?: Trip | undefined;
};

/**
 * Describes the message admin.v1.UpdateTripResponse.
 * Use `create(UpdateTripResponseSchema)` to create a new message.
 */
export declare const UpdateTripResponseSchema: GenMessage<UpdateTripResponse>;

/**
 * @generated from message admin.v1.DeleteTripRequest
 */
export declare type DeleteTripRequest = Message<"admin.v1.DeleteTripRequest"> & {
  /**
   * @generated from field: string trip_id = 1;
   */
  tripId: string;
};

/**
 * Describes the message admin.v1.DeleteTripRequest.
 * Use `create(DeleteTripRequestSchema)` to create a new message.
 */
export declare const DeleteTripRequestSchema: GenMessage<DeleteTripRequest>;

/**
 * @generated from message admin.v1.DeleteTripResponse
 */
export declare type DeleteTripResponse = Message<"admin.v1.DeleteTripResponse"> & {
};

/**
 * Describes the message admin.v1.DeleteTripResponse.
 * Use `create(DeleteTripResponseSchema)` to create a new message.
 */
export declare const DeleteTripResponseSchema: GenMessage<DeleteTripResponse>;

/**
 * @generated from enum admin.v1.TripDirection
 */
export enum TripDirection {
  /**
   * @generated from enum value: TRIP_DIRECTION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: TRIP_DIRECTION_OUTBOUND = 1;
   */
  OUTBOUND = 1,

  /**
   * @generated from enum value: TRIP_DIRECTION_INBOUND = 2;
   */
  INBOUND = 2,
}

/**
 * Describes the enum admin.v1.TripDirection.
 */
export declare const TripDirectionSchema: GenEnum<TripDirection>;

/**
 * @generated from service admin.v1.TripService
 */
export declare const TripService: GenService<{
  /**
   * @generated from rpc admin.v1.TripService.ListTrips
   */
  listTrips: {
    methodKind: "unary";
    input: typeof ListTripsRequestSchema;
    output: typeof ListTripsResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.TripService.GetTrip
   */
  getTrip: {
    methodKind: "unary";
    input: typeof GetTripRequestSchema;
    output: typeof GetTripResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.TripService.CreateTrip
   */
  createTrip: {
    methodKind: "unary";
    input: typeof CreateTripRequestSchema;
    output: typeof CreateTripResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.TripService.UpdateTrip
   */
  updateTrip: {
    methodKind: "unary";
    input: typeof UpdateTripRequestSchema;
    output: typeof UpdateTripResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.TripService.DeleteTrip
   */
  deleteTrip: {
    methodKind: "unary";
    input: typeof DeleteTripRequestSchema;
    output: typeof DeleteTripResponseSchema;
  },
}>;

