// @generated by protoc-gen-es v2.16.0
// @generated from file admin/v1/user.proto (package admin.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_admin_v1_common } from "./common_pb";
import { file_google_protobuf_field_mask } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file admin/v1/user.proto.
 */
export const file_admin_v1_user = /*@__PURE__*/
  fileDesc("ChNhZG1pbi92MS91c2VyLnByb3RvEghhZG1pbi52MSKxAQoEVXNlchIKCgJpZBgBIAEoCRINCgVlbWFpbBgCIAEoCRIjCgVncmFkZRgDIAEoDjIPLmFkbWluLnYxLkdyYWRlSACIAQESJQoGY291cnNlGAQgASgOMhAuYWRtaW4udjEuQ291cnNlSAGIAQESIwoFY2xhc3MYBSABKA4yDy5hZG1pbi52MS5DbGFzc0gCiAEBQggKBl9ncmFkZUIJCgdfY291cnNlQggKBl9jbGFzcyI5ChBMaXN0VXNlcnNSZXF1ZXN0EhEKCXBhZ2Vfc2l6ZRgBIAEoBRISCgpwYWdlX3Rva2VuGAIgASgJIksKEUxpc3RVc2Vyc1Jlc3BvbnNlEh0KBXVzZXJzGAEgAygLMg4uYWRtaW4udjEuVXNlchIXCg9uZXh0X3BhZ2VfdG9rZW4YAiABKAkiHAoOR2V0VXNlclJlcXVlc3QSCgoCaWQYASABKAkiLwoPR2V0VXNlclJlc3BvbnNlEhwKBHVzZXIYASABKAsyDi5hZG1pbi52MS5Vc2VyIr4BChFDcmVhdGVVc2VyUmVxdWVzdBIKCgJpZBgBIAEoCRINCgVlbWFpbBgCIAEoCRIjCgVncmFkZRgDIAEoDjIPLmFkbWluLnYxLkdyYWRlSACIAQESJQoGY291cnNlGAQgASgOMhAuYWRtaW4udjEuQ291cnNlSAGIAQESIwoFY2xhc3MYBSABKA4yDy5hZG1pbi52MS5DbGFzc0gCiAEBQggKBl9ncmFkZUIJCgdfY291cnNlQggKBl9jbGFzcyIyChJDcmVhdGVVc2VyUmVzcG9uc2USHAoEdXNlchgBIAEoCzIOLmFkbWluLnYxLlVzZXIi7wEKEVVwZGF0ZVVzZXJSZXF1ZXN0EgoKAmlkGAEgASgJEg0KBWVtYWlsGAIgASgJEiMKBWdyYWRlGAMgASgOMg8uYWRtaW4udjEuR3JhZGVIAIgBARIlCgZjb3Vyc2UYBCABKA4yEC5hZG1pbi52MS5Db3Vyc2VIAYgBARIjCgVjbGFzcxgFIAEoDjIPLmFkbWluLnYxLkNsYXNzSAKIAQESLwoLdXBkYXRlX21hc2sYYyABKAsyGi5nb29nbGUucHJvdG9idWYuRmllbGRNYXNrQggKBl9ncmFkZUIJCgdfY291cnNlQggKBl9jbGFzcyIyChJVcGRhdGVVc2VyUmVzcG9uc2USHAoEdXNlchgBIAEoCzIOLmFkbWluLnYxLlVzZXIiHwoRRGVsZXRlVXNlclJlcXVlc3QSCgoCaWQYASABKAkiFAoSRGVsZXRlVXNlclJlc3BvbnNlMu4CCgtVc2VyU2VydmljZRJECglMaXN0VXNlcnMSGi5hZG1pbi52MS5MaXN0VXNlcnNSZXF1ZXN0GhsuYWRtaW4udjEuTGlzdFVzZXJzUmVzcG9uc2USPgoHR2V0VXNlchIYLmFkbWluLnYxLkdldFVzZXJSZXF1ZXN0GhkuYWRtaW4udjEuR2V0VXNlclJlc3BvbnNlEkcKCkNyZWF0ZVVzZXISGy5hZG1pbi52MS5DcmVhdGVVc2VyUmVxdWVzdBocLmFkbWluLnYxLkNyZWF0ZVVzZXJSZXNwb25zZRJHCgpVcGRhdGVVc2VyEhsuYWRtaW4udjEuVXBkYXRlVXNlclJlcXVlc3QaHC5hZG1pbi52MS5VcGRhdGVVc2VyUmVzcG9uc2USRwoKRGVsZXRlVXNlchIbLmFkbWluLnYxLkRlbGV0ZVVzZXJSZXF1ZXN0GhwuYWRtaW4udjEuRGVsZXRlVXNlclJlc3BvbnNlYgZwcm90bzM", [file_admin_v1_common, file_google_protobuf_field_mask]);

/**
 * Describes the message admin.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_user, 0);

/**
 * Describes the message admin.v1.ListUsersRequest.
 * Use `create(ListUsersRequestSchema)` to create a new message.
 */
export const ListUsersRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_user, 1);

/**
 * Describes the message admin.v1.ListUsersResponse.
 * Use `create(ListUsersResponseSchema)` to create a new message.
 */
export const ListUsersResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_user, 2);

/**
 * Describes the message admin.v1.GetUserRequest.
 * Use `create(GetUserRequestSchema)` to create a new message.
 */
export const GetUserRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_user, 3);

/**
 * Describes the message admin.v1.GetUserResponse.
 * Use `create(GetUserResponseSchema)` to create a new message.
 */
export const GetUserResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_user, 4);

/**
 * Describes the message admin.v1.CreateUserRequest.
 * Use `create(CreateUserRequestSchema)` to create a new message.
 */
export const CreateUserRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_user, 5);

/**
 * Describes the message admin.v1.CreateUserResponse.
 * Use `create(CreateUserResponseSchema)` to create a new message.
 */
export const CreateUserResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_user, 6);

/**
 * Describes the message admin.v1.UpdateUserRequest.
 * Use `create(UpdateUserRequestSchema)` to create a new message.
 */
export const UpdateUserRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_user, 7);

/**
 * Describes the message admin.v1.UpdateUserResponse.
 * Use `create(UpdateUserResponseSchema)` to create a new message.
 */
export const UpdateUserResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_user, 8);

/**
 * Describes the message admin.v1.DeleteUserRequest.
 * Use `create(DeleteUserRequestSchema)` to create a new message.
 */
export const DeleteUserRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_user, 9);

/**
 * Describes the message admin.v1.DeleteUserResponse.
 * Use `create(DeleteUserResponseSchema)` to create a new message.
 */
export const DeleteUserResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_user, 10);

/**
 * @generated from service admin.v1.UserService
 */
export const UserService = /*@__PURE__*/
  serviceDesc(file_admin_v1_user, 0);

