// @generated by protoc-gen-es v2.16.0
// @generated from file admin/v1/zone.proto (package admin.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_field_mask } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file admin/v1/zone.proto.
 */
export const file_admin_v1_zone = /*@__PURE__*/
  fileDesc("ChNhZG1pbi92MS96b25lLnByb3RvEghhZG1pbi52MSIXCgRab25lEg8KB3pvbmVfaWQYASABKAkiOQoQTGlzdFpvbmVzUmVxdWVzdBIRCglwYWdlX3NpemUYASABKAUSEgoKcGFnZV90b2tlbhgCIAEoCSJLChFMaXN0Wm9uZXNSZXNwb25zZRIdCgV6b25lcxgBIAMoCzIOLmFkbWluLnYxLlpvbmUSFwoPbmV4dF9wYWdlX3Rva2VuGAIgASgJIiEKDkdldFpvbmVSZXF1ZXN0Eg8KB3pvbmVfaWQYASABKAkiLwoPR2V0Wm9uZVJlc3BvbnNlEhwKBHpvbmUYASABKAsyDi5hZG1pbi52MS5ab25lIiQKEUNyZWF0ZVpvbmVSZXF1ZXN0Eg8KB3pvbmVfaWQYASABKAkiMgoSQ3JlYXRlWm9uZVJlc3BvbnNlEhwKBHpvbmUYASABKAsyDi5hZG1pbi52MS5ab25lIlUKEVVwZGF0ZVpvbmVSZXF1ZXN0Eg8KB3pvbmVfaWQYASABKAkSLwoLdXBkYXRlX21hc2sYYyABKAsyGi5nb29nbGUucHJvdG9idWYuRmllbGRNYXNrIjIKElVwZGF0ZVpvbmVSZXNwb25zZRIcCgR6b25lGAEgASgLMg4uYWRtaW4udjEuWm9uZSIkChFEZWxldGVab25lUmVxdWVzdBIPCgd6b25lX2lkGAEgASgJIhQKEkRlbGV0ZVpvbmVSZXNwb25zZTLuAgoLWm9uZVNlcnZpY2USRAoJTGlzdFpvbmVzEhouYWRtaW4udjEuTGlzdFpvbmVzUmVxdWVzdBobLmFkbWluLnYxLkxpc3Rab25lc1Jlc3BvbnNlEj4KB0dldFpvbmUSGC5hZG1pbi52MS5HZXRab25lUmVxdWVzdBoZLmFkbWluLnYxLkdldFpvbmVSZXNwb25zZRJHCgpDcmVhdGVab25lEhsuYWRtaW4udjEuQ3JlYXRlWm9uZVJlcXVlc3QaHC5hZG1pbi52MS5DcmVhdGVab25lUmVzcG9uc2USRwoKVXBkYXRlWm9uZRIbLmFkbWluLnYxLlVwZGF0ZVpvbmVSZXF1ZXN0GhwuYWRtaW4udjEuVXBkYXRlWm9uZVJlc3BvbnNlEkcKCkRlbGV0ZVpvbmUSGy5hZG1pbi52MS5EZWxldGVab25lUmVxdWVzdBocLmFkbWluLnYxLkRlbGV0ZVpvbmVSZXNwb25zZWIGcHJvdG8z", [file_google_protobuf_field_mask]);

/**
 * Describes the message admin.v1.Zone.
 * Use `create(ZoneSchema)` to create a new message.
 */
export const ZoneSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_zone, 0);

/**
 * Describes the message admin.v1.ListZonesRequest.
 * Use `create(ListZonesRequestSchema)` to create a new message.
 */
export const ListZonesRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_zone, 1);

/**
 * Describes the message admin.v1.ListZonesResponse.
 * Use `create(ListZonesResponseSchema)` to create a new message.
 */
export const ListZonesResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_zone, 2);

/**
 * Describes the message admin.v1.GetZoneRequest.
 * Use `create(GetZoneRequestSchema)` to create a new message.
 */
export const GetZoneRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_zone, 3);

/**
 * Describes the message admin.v1.GetZoneResponse.
 * Use `create(GetZoneResponseSchema)` to create a new message.
 */
export const GetZoneResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_zone, 4);

/**
 * Describes the message admin.v1.CreateZoneRequest.
 * Use `create(CreateZoneRequestSchema)` to create a new message.
 */
export const CreateZoneRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_zone, 5);

/**
 * Describes the message admin.v1.CreateZoneResponse.
 * Use `create(CreateZoneResponseSchema)` to create a new message.
 */
export const CreateZoneResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_zone, 6);

/**
 * Describes the message admin.v1.UpdateZoneRequest.
 * Use `create(UpdateZoneRequestSchema)` to create a new message.
 */
export const UpdateZoneRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_zone, 7);

/**
 * Describes the message admin.v1.UpdateZoneResponse.
 * Use `create(UpdateZoneResponseSchema)` to create a new message.
 */
export const UpdateZoneResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_zone, 8);

/**
 * Describes the message admin.v1.DeleteZoneRequest.
 * Use `create(DeleteZoneRequestSchema)` to create a new message.
 */
export const DeleteZoneRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_zone, 9);

/**
 * Describes the message admin.v1.DeleteZoneResponse.
 * Use `create(DeleteZoneResponseSchema)` to create a new message.
 */
export const DeleteZoneResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_zone, 10);

/**
 * @generated from service admin.v1.ZoneService
 */
export const ZoneService = /*@__PURE__*/
  serviceDesc(file_admin_v1_zone, 0);

