// @generated by protoc-gen-es v2.16.0
// @generated from file admin/v1/zone.proto (package admin.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { FieldMask } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file admin/v1/zone.proto.
 */
export declare const file_admin_v1_zone: GenFile;

/**
 * @generated from message admin.v1.Zone
 */
export declare type Zone = Message<"admin.v1.Zone"> & {
  /**
   * @generated from field: string zone_id = 1;
   */
  zoneId: string;
};

/**
 * Describes the message admin.v1.Zone.
 * Use `create(ZoneSchema)` to create a new message.
 */
export declare const ZoneSchema: GenMessage<Zone>;

/**
 * @generated from message admin.v1.ListZonesRequest
 */
export declare type ListZonesRequest = Message<"admin.v1.ListZonesRequest"> & {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;
};

/**
 * Describes the message admin.v1.ListZonesRequest.
 * Use `create(ListZonesRequestSchema)` to create a new message.
 */
export declare const ListZonesRequestSchema: GenMessage<ListZonesRequest>;

/**
 * @generated from message admin.v1.ListZonesResponse
 */
export declare type ListZonesResponse = Message<"admin.v1.ListZonesResponse"> & {
  /**
   * @generated from field: repeated admin.v1.Zone zones = 1;
   */
  zones: Zone[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message admin.v1.ListZonesResponse.
 * Use `create(ListZonesResponseSchema)` to create a new message.
 */
export declare const ListZonesResponseSchema: GenMessage<ListZonesResponse>;

/**
 * @generated from message admin.v1.GetZoneRequest
 */
export declare type GetZoneRequest = Message<"admin.v1.GetZoneRequest"> & {
  /**
   * @generated from field: string zone_id = 1;
   */
  zoneId: string;
};

/**
 * Describes the message admin.v1.GetZoneRequest.
 * Use `create(GetZoneRequestSchema)` to create a new message.
 */
export declare const GetZoneRequestSchema: GenMessage<GetZoneRequest>;

/**
 * @generated from message admin.v1.GetZoneResponse
 */
export declare type GetZoneResponse = Message<"admin.v1.GetZoneResponse"> & {
  /**
   * @generated from field: admin.v1.Zone zone = 1;
   */
  zone?: Zone | undefined;
};

/**
 * Describes the message admin.v1.GetZoneResponse.
 * Use `create(GetZoneResponseSchema)` to create a new message.
 */
export declare const GetZoneResponseSchema: GenMessage<GetZoneResponse>;

/**
 * @generated from message admin.v1.CreateZoneRequest
 */
export declare type CreateZoneRequest = Message<"admin.v1.CreateZoneRequest"> & {
  /**
   * @generated from field: string zone_id = 1;
   */
  zoneId: string;
};

/**
 * Describes the message admin.v1.CreateZoneRequest.
 * Use `create(CreateZoneRequestSchema)` to create a new message.
 */
export declare const CreateZoneRequestSchema: GenMessage<CreateZoneRequest>;

/**
 * @generated from message admin.v1.CreateZoneResponse
 */
export declare type CreateZoneResponse = Message<"admin.v1.CreateZoneResponse"> & {
  /**
   * @generated from field: admin.v1.Zone zone = 1;
   */
  zone?: Zone | undefined;
};

/**
 * Describes the message admin.v1.CreateZoneResponse.
 * Use `create(CreateZoneResponseSchema)` to create a new message.
 */
export declare const CreateZoneResponseSchema: GenMessage<CreateZoneResponse>;

/**
 * @generated from message admin.v1.UpdateZoneRequest
 */
export declare type UpdateZoneRequest = Message<"admin.v1.UpdateZoneRequest"> & {
  /**
   * @generated from field: string zone_id = 1;
   */
  zoneId: string;

  /**
   * @generated from field: google.protobuf.FieldMask update_mask = 99;
   */
  updateMask?: FieldMask | undefined;
};

/**
 * Describes the message admin.v1.UpdateZoneRequest.
 * Use `create(UpdateZoneRequestSchema)` to create a new message.
 */
export declare const UpdateZoneRequestSchema: GenMessage<UpdateZoneRequest>;

/**
 * @generated from message admin.v1.UpdateZoneResponse
 */
export declare type UpdateZoneResponse = Message<"admin.v1.UpdateZoneResponse"> & {
  /**
   * @generated from field: admin.v1.Zone zone = 1;
   */
  zone?: Zone | undefined;
};

/**
 * Describes the message admin.v1.UpdateZoneResponse.
 * Use `create(UpdateZoneResponseSchema)` to create a new message.
 */
export declare const UpdateZoneResponseSchema: GenMessage<UpdateZoneResponse>;

/**
 * @generated from message admin.v1.DeleteZoneRequest
 */
export declare type DeleteZoneRequest = Message<"admin.v1.DeleteZoneRequest"> & {
  /**
   * @generated from field: string zone_id = 1;
   */
  zoneId: string;
};

/**
 * Describes the message admin.v1.DeleteZoneRequest.
 * Use `create(DeleteZoneRequestSchema)` to create a new message.
 */
export declare const DeleteZoneRequestSchema: GenMessage<DeleteZoneRequest>;

/**
 * @generated from message admin.v1.DeleteZoneResponse
 */
export declare type DeleteZoneResponse = Message<"admin.v1.DeleteZoneResponse"> & {
};

/**
 * Describes the message admin.v1.DeleteZoneResponse.
 * Use `create(DeleteZoneResponseSchema)` to create a new message.
 */
export declare const DeleteZoneResponseSchema: GenMessage<DeleteZoneResponse>;

/**
 * @generated from service admin.v1.ZoneService
 */
export declare const ZoneService: GenService<{
  /**
   * @generated from rpc admin.v1.ZoneService.ListZones
   */
  listZones: {
    methodKind: "unary";
    input: typeof ListZonesRequestSchema;
    output: typeof ListZonesResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.ZoneService.GetZone
   */
  getZone: {
    methodKind: "unary";
    input: typeof GetZoneRequestSchema;
    output: typeof GetZoneResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.ZoneService.CreateZone
   */
  createZone: {
    methodKind: "unary";
    input: typeof CreateZoneRequestSchema;
    output: typeof CreateZoneResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.ZoneService.UpdateZone
   */
  updateZone: {
    methodKind: "unary";
    input: typeof UpdateZoneRequestSchema;
    output: typeof UpdateZoneResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.ZoneService.DeleteZone
   */
  deleteZone: {
    methodKind: "unary";
    input: typeof DeleteZoneRequestSchema;
    output: typeof DeleteZoneResponseSchema;
  },
}>;

