// @generated by protoc-gen-es v2.16.0
// @generated from file google/type/dayofweek.proto (package google.type, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file google/type/dayofweek.proto.
 */
export declare const file_google_type_dayofweek: GenFile;

/**
 * @generated from enum google.type.DayOfWeek
 */
export enum DayOfWeek {
  /**
   * @generated from enum value: DAY_OF_WEEK_UNSPECIFIED = 0;
   */
  DAY_OF_WEEK_UNSPECIFIED = 0,

  /**
   * @generated from enum value: MONDAY = 1;
   */
  MONDAY = 1,

  /**
   * @generated from enum value: TUESDAY = 2;
   */
  TUESDAY = 2,

  /**
   * @generated from enum value: WEDNESDAY = 3;
   */
  WEDNESDAY = 3,

  /**
   * @generated from enum value: THURSDAY = 4;
   */
  THURSDAY = 4,

  /**
   * @generated from enum value: FRIDAY = 5;
   */
  FRIDAY = 5,

  /**
   * @generated from enum value: SATURDAY = 6;
   */
  SATURDAY = 6,

  /**
   * @generated from enum value: SUNDAY = 7;
   */
  SUNDAY = 7,
}

/**
 * Describes the enum google.type.DayOfWeek.
 */
export declare const DayOfWeekSchema: GenEnum<DayOfWeek>;

