// @generated by protoc-gen-es v2.16.0
// @generated from file google/type/latlng.proto (package google.type, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file google/type/latlng.proto.
 */
export const file_google_type_latlng = /*@__PURE__*/
  fileDesc("Chhnb29nbGUvdHlwZS9sYXRsbmcucHJvdG8SC2dvb2dsZS50eXBlIi0KBkxhdExuZxIQCghsYXRpdHVkZRgBIAEoARIRCglsb25naXR1ZGUYAiABKAFiBnByb3RvMw");

/**
 * Describes the message google.type.LatLng.
 * Use `create(LatLngSchema)` to create a new message.
 */
export const LatLngSchema = /*@__PURE__*/
  messageDesc(file_google_type_latlng, 0);

