// @generated by protoc-gen-es v2.16.0
// @generated from file google/type/latlng.proto (package google.type, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file google/type/latlng.proto.
 */
export declare const file_google_type_latlng: GenFile;

/**
 * @generated from message google.type.LatLng
 */
export declare type LatLng = Message<"google.type.LatLng"> & {
  /**
   * @generated from field: double latitude = 1;
   */
  latitude: number;

  /**
   * @generated from field: double longitude = 2;
   */
  longitude: number;
};

/**
 * Describes the message google.type.LatLng.
 * Use `create(LatLngSchema)` to create a new message.
 */
export declare const LatLngSchema: GenMessage<LatLng>;

